import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { LandingPage } from '@/components/LandingPage';
import { LOCALES, PATHS, STORE_URL, absoluteUrl, alternatesFor, getCopy, getPageCopy, localizedPath, type Locale } from '@/lib/site';
import { getLocalizedPrivacy, getLocalizedSupport } from '@/lib/localized-pages';

export function generateStaticParams() { return LOCALES.flatMap(locale => PATHS.map(slug => ({ locale, slug: slug ? slug.split('/') : [] }))); }
const supportTitle: Record<Locale, string> = { en: 'Need a hand?', 'zh-CN': '需要帮助？', 'zh-TW': '需要協助嗎？', ja: 'お困りですか？', ko: '도움이 필요하신가요?', de: 'Brauchst du Hilfe?', fr: 'Besoin d’aide ?', es: '¿Necesitas ayuda?', 'pt-BR': 'Precisa de ajuda?' };
const privacyTitle: Record<Locale, string> = { en: 'Privacy at SEO Copilot', 'zh-CN': 'SEO Copilot 隐私说明', 'zh-TW': 'SEO Copilot 隱私說明', ja: 'SEO Copilot のプライバシー', ko: 'SEO Copilot 개인정보 보호', de: 'Datenschutz bei SEO Copilot', fr: 'Confidentialité chez SEO Copilot', es: 'Privacidad en SEO Copilot', 'pt-BR': 'Privacidade no SEO Copilot' };
const privacyHead: Record<Locale, [string, string, string]> = { en: ['Privacy', 'Basic SEO scanning', 'Optional AI Fix'], 'zh-CN': ['隐私', '基础 SEO 扫描', '可选的 AI Fix'], 'zh-TW': ['隱私權', '基礎 SEO 掃描', '可選的 AI Fix'], ja: ['プライバシー', '基本 SEO スキャン', '任意の AI Fix'], ko: ['개인정보 보호', '기본 SEO 스캔', '선택 사항인 AI Fix'], de: ['Datenschutz', 'Basisprüfung', 'Optionaler AI Fix'], fr: ['Confidentialité', 'Analyse SEO de base', 'AI Fix facultatif'], es: ['Privacidad', 'Análisis SEO básico', 'AI Fix opcional'], 'pt-BR': ['Privacidade', 'Análise básica de SEO', 'AI Fix opcional'] };
export async function generateMetadata({ params }: { params: Promise<{ locale: string; slug?: string[] }> }): Promise<Metadata> { const { locale, slug = [] } = await params; const path = slug.join('/'); if (!(locale === 'en' || LOCALES.includes(locale as typeof LOCALES[number])) || !PATHS.includes(path)) return {}; const lang = locale as Locale; const c = getCopy(lang); const p = path === 'privacy' ? { title: privacyTitle[lang], description: c.privateBody } : path === 'support' ? { title: supportTitle[lang], description: c.faq[0]?.[1] ?? '' } : path ? getPageCopy(lang, path) : { title: 'SEO Copilot', description: c.homeIntro }; const title = p.title; const description = 'description' in p ? p.description : p.intro; const alt = alternatesFor(path); return { title, description, alternates: { canonical: absoluteUrl(lang, path), languages: alt.languages }, openGraph: { title: `${title} | SEO Copilot`, description, url: absoluteUrl(lang, path), type: 'website' } }; }
export default async function LocalizedPage({ params }: { params: Promise<{ locale: string; slug?: string[] }> }) { const { locale, slug = [] } = await params; if (!(locale === 'en' || LOCALES.includes(locale as typeof LOCALES[number]))) notFound(); const lang = locale as Locale; const path = slug.join('/'); if (!PATHS.includes(path)) notFound(); const c = getCopy(lang); if (!path) return <LocalizedHome locale={lang} />;
  if (path === 'privacy') { const p = getLocalizedPrivacy(lang); return <main className="page"><div className="wrap prose"><p className="eyebrow">{p.eyebrow}</p><h1>{p.title}</h1><p>{p.effective}</p><h2>{p.scanHeading}</h2><p>{p.scan}</p><h2>{p.aiHeading}</h2><p>{p.ai}</p><h2>{p.storageHeading}</h2><p>{p.storage}</p><p>{p.limits} <a href="https://github.com/sumei7550/SEO-Copilot/blob/main/docs/PRIVACY_DATA_MAP.md" target="_blank" rel="noopener noreferrer">data map</a>.</p><h2>{p.notHeading}</h2><ul>{p.notDo.map(item => <li key={item}>{item}</li>)}</ul><h2>{p.contact}</h2><p><a href="https://github.com/sumei7550/SEO-Copilot/issues" target="_blank" rel="noopener noreferrer">{p.contactLink}</a></p></div></main>; }
  if (path === 'support') { const s = getLocalizedSupport(lang); return <main className="page"><div className="wrap prose"><p className="eyebrow">{s.eyebrow}</p><h1>{s.title}</h1><p>{s.intro}</p><div className="faq">{s.faq.map(([q, a]) => <article className="card" key={q}><h3>{q}</h3><p>{a}</p></article>)}</div><div className="actions"><a className="button button-primary" href={STORE_URL} target="_blank" rel="noopener noreferrer">{s.install}</a><a className="button" href={localizedPath(lang, 'privacy')}>{s.privacy}</a><a className="button" href="https://github.com/sumei7550/SEO-Copilot/issues" target="_blank" rel="noopener noreferrer">{s.github}</a></div></div></main>; }
  const p = getPageCopy(lang, path); return <LandingPage eyebrow={p.eyebrow} title={p.title} intro={p.intro} bullets={p.bullets} what={p.what} reassurance={p.reassurance} cta={p.supportCta} related={path !== 'features' ? [[localizedPath(lang, 'features'), c.nav.features]] : []} relatedLabel={p.related} />;
}
function LocalizedHome({ locale }: { locale: Locale }) { const c = getCopy(locale); return <main className="page localized-home"><div className="wrap prose"><p className="eyebrow">{c.eyebrow}</p><h1>{c.homeTitle}</h1><p className="hero-copy">{c.homeIntro}</p><div className="actions"><a className="button button-primary" href="https://chromewebstore.google.com/detail/kjkjgpmhjilegalgphglnagjnfgnighb?utm_source=website" target="_blank" rel="noopener noreferrer">{c.cta}</a></div><div className="cards localized-cards">{[c.score, c.issues, c.suggestions].map((x, i) => <article className="card" key={x}><div className="icon">0{i + 1}</div><h2>{x}</h2><p>{[c.howIntro, c.checks, c.privateBody][i]}</p></article>)}</div><div className="card landing-summary"><h2>{c.how}</h2><p>{c.howIntro}</p><ul><li>{c.score}</li><li>{c.issues}</li><li>{c.suggestions}</li></ul></div><div className="faq">{c.faq.map(([q, a]) => <article className="card" key={q}><h3>{q}</h3><p>{a}</p></article>)}</div></div></main>; }
