import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { LandingPage } from '@/components/LandingPage';
import { LOCALES, PATHS, STORE_URL, absoluteUrl, alternatesFor, getCopy, getHomeMetadata, getPageCopy, localizedPath, supportDescriptions, type Locale } from '@/lib/site';
import { getLocalizedPrivacy, getLocalizedSupport } from '@/lib/localized-pages';

export function generateStaticParams() { return LOCALES.flatMap(locale => PATHS.map(slug => ({ locale, slug: slug ? slug.split('/') : [] }))); }
function relatedLinks(locale: Locale, path: string): [string, string][] { const links: Record<string, string[]> = { 'seo-checker': ['seo-audit', 'on-page-seo-checker'], 'seo-audit': ['seo-checker', 'on-page-seo-checker'], 'on-page-seo-checker': ['seo-audit', 'seo-checker'], 'title-tag-checker': ['meta-description-checker'], 'meta-description-checker': ['title-tag-checker'] }; return (links[path] ?? []).map(target => [localizedPath(locale, target), getPageCopy(locale, target).title]); }
const supportTitle: Record<Locale, string> = { en: 'Need a hand?', 'zh-CN': '需要帮助？', 'zh-TW': '需要協助嗎？', ja: 'お困りですか？', ko: '도움이 필요하신가요?', de: 'Brauchst du Hilfe?', fr: 'Besoin d’aide ?', es: '¿Necesitas ayuda?', 'pt-BR': 'Precisa de ajuda?' };
const privacyTitle: Record<Locale, string> = { en: 'Privacy at SEO Copilot', 'zh-CN': 'SEO Copilot 隐私说明', 'zh-TW': 'SEO Copilot 隱私說明', ja: 'SEO Copilot のプライバシー', ko: 'SEO Copilot 개인정보 보호', de: 'Datenschutz bei SEO Copilot', fr: 'Confidentialité chez SEO Copilot', es: 'Privacidad en SEO Copilot', 'pt-BR': 'Privacidade no SEO Copilot' };
const termsTitle: Record<Locale, string> = { en: 'Terms of Use', 'zh-CN': '使用条款', 'zh-TW': '使用條款', ja: '利用規約', ko: '이용 약관', de: 'Nutzungsbedingungen', fr: 'Conditions d’utilisation', es: 'Términos de uso', 'pt-BR': 'Termos de uso' };
const termsCopy: Record<Locale, [string, string, string, string, string, string, string]> = {
  en: ['By using SEO Copilot, you agree to these basic terms of use.', 'Acceptable use', 'Use the extension lawfully and do not interfere with the service, abuse request limits, or attempt unauthorized access.', 'Service limits', 'SEO Copilot provides page-level SEO guidance and does not guarantee rankings, traffic, or any particular outcome. You review suggestions before using them.', 'Contact', 'GitHub support'],
  'zh-CN': ['使用 SEO Copilot 即表示你同意以下基本使用规则。', '合理使用', '请仅在合法、合规的场景中使用本扩展，不得干扰服务、滥用请求限制或尝试未经授权地访问系统。', '服务说明', 'SEO Copilot 提供页面级 SEO 建议，不保证排名、流量或特定结果。你负责审核并决定是否采用建议。', '联系我们', 'GitHub 支持'],
  'zh-TW': ['使用 SEO Copilot 即表示你同意以下基本使用規則。', '合理使用', '請僅在合法、合規的情境中使用本擴充功能，不得干擾服務、濫用請求限制或嘗試未經授權存取系統。', '服務說明', 'SEO Copilot 提供頁面級 SEO 建議，不保證排名、流量或特定結果。你負責審核並決定是否採用建議。', '聯絡我們', 'GitHub 支援'],
  ja: ['SEO Copilot を使用することで、以下の基本的な利用規約に同意したものとします。', '適切な利用', '拡張機能は合法的に利用し、サービスへの干渉、リクエスト制限の悪用、未承認のアクセスを行わないでください。', 'サービスの制限', 'SEO Copilot はページ単位の SEO 提案を提供しますが、順位、トラフィック、その他の結果を保証しません。', 'お問い合わせ', 'GitHub サポート'],
  ko: ['SEO Copilot을 사용하면 다음 기본 이용 약관에 동의하는 것입니다.', '허용되는 사용', '확장 프로그램을 합법적으로 사용하고 서비스를 방해하거나 요청 제한을 악용하거나 승인되지 않은 접근을 시도하지 마세요.', '서비스 제한', 'SEO Copilot은 페이지 단위 SEO 안내를 제공하며 순위, 트래픽 또는 특정 결과를 보장하지 않습니다.', '문의', 'GitHub 지원'],
  de: ['Mit der Nutzung von SEO Copilot stimmst du diesen grundlegenden Nutzungsbedingungen zu.', 'Zulässige Nutzung', 'Nutze die Erweiterung rechtmäßig und störe den Dienst nicht, missbrauche keine Anfrage-Limits und versuche keinen unbefugten Zugriff.', 'Grenzen des Dienstes', 'SEO Copilot bietet Seiten-SEO-Empfehlungen, garantiert aber keine Rankings, keinen Traffic und kein bestimmtes Ergebnis.', 'Kontakt', 'GitHub-Support'],
  fr: ['En utilisant SEO Copilot, vous acceptez ces conditions d’utilisation de base.', 'Utilisation acceptable', 'Utilisez l’extension légalement, sans perturber le service, abuser des limites de requêtes ni tenter un accès non autorisé.', 'Limites du service', 'SEO Copilot fournit des conseils SEO page par page, sans garantir le classement, le trafic ni un résultat particulier.', 'Contact', 'Assistance GitHub'],
  es: ['Al usar SEO Copilot, aceptas estas condiciones básicas de uso.', 'Uso aceptable', 'Usa la extensión de forma legal, sin interferir con el servicio, abusar de los límites de solicitudes ni intentar acceder sin autorización.', 'Límites del servicio', 'SEO Copilot ofrece orientación SEO por página, pero no garantiza posiciones, tráfico ni un resultado concreto.', 'Contacto', 'Soporte de GitHub'],
  'pt-BR': ['Ao usar o SEO Copilot, você concorda com estes termos básicos de uso.', 'Uso aceitável', 'Use a extensão de forma legal e não interfira no serviço, abuse dos limites de solicitações nem tente acessar sistemas sem autorização.', 'Limites do serviço', 'O SEO Copilot oferece orientação de SEO por página, mas não garante posições, tráfego ou qualquer resultado específico.', 'Contato', 'Suporte no GitHub'],
};
const privacyHead: Record<Locale, [string, string, string]> = { en: ['Privacy', 'Basic SEO scanning', 'Optional AI Fix'], 'zh-CN': ['隐私', '基础 SEO 扫描', '可选的 AI Fix'], 'zh-TW': ['隱私權', '基礎 SEO 掃描', '可選的 AI Fix'], ja: ['プライバシー', '基本 SEO スキャン', '任意の AI Fix'], ko: ['개인정보 보호', '기본 SEO 스캔', '선택 사항인 AI Fix'], de: ['Datenschutz', 'Basisprüfung', 'Optionaler AI Fix'], fr: ['Confidentialité', 'Analyse SEO de base', 'AI Fix facultatif'], es: ['Privacidad', 'Análisis SEO básico', 'AI Fix opcional'], 'pt-BR': ['Privacidade', 'Análise básica de SEO', 'AI Fix opcional'] };
export async function generateMetadata({ params }: { params: Promise<{ locale: string; slug?: string[] }> }): Promise<Metadata> { const { locale, slug = [] } = await params; const path = slug.join('/'); if (!(locale === 'en' || LOCALES.includes(locale as typeof LOCALES[number])) || !PATHS.includes(path)) return {}; const lang = locale as Locale; const c = getCopy(lang); const home = getHomeMetadata(lang); const p = !path ? home : path === 'privacy' ? { title: privacyTitle[lang], description: c.privateBody } : path === 'terms' ? { title: termsTitle[lang], description: lang === 'zh-CN' ? 'SEO Copilot 使用条款。' : 'Terms of use for SEO Copilot.' } : path === 'support' ? { title: supportTitle[lang], description: supportDescriptions[lang] } : getPageCopy(lang, path); const title = p.title; const description = 'description' in p ? p.description : p.intro; const alt = alternatesFor(path); return { title, description, alternates: { canonical: absoluteUrl(lang, path), languages: alt.languages }, openGraph: { title: `${title} | SEO Copilot`, description, url: absoluteUrl(lang, path), type: 'website' } }; }
export default async function LocalizedPage({ params }: { params: Promise<{ locale: string; slug?: string[] }> }) { const { locale, slug = [] } = await params; if (!(locale === 'en' || LOCALES.includes(locale as typeof LOCALES[number]))) notFound(); const lang = locale as Locale; const path = slug.join('/'); if (!PATHS.includes(path)) notFound(); const c = getCopy(lang); if (!path) return <LocalizedHome locale={lang} />;
  if (path === 'terms') { const t = termsCopy[lang]; return <main className="page"><div className="wrap prose"><p className="eyebrow">{termsTitle[lang]}</p><h1>{termsTitle[lang]}</h1><p>{t[0]}</p><h2>{t[1]}</h2><p>{t[2]}</p><h2>{t[3]}</h2><p>{t[4]}</p><h2>{t[5]}</h2><p><a href="https://github.com/sumei7550/SEO-Copilot/issues" target="_blank" rel="noopener noreferrer">{t[6]}</a></p></div></main>; }
  if (path === 'privacy') { const p = getLocalizedPrivacy(lang); return <main className="page"><div className="wrap prose"><p className="eyebrow">{p.eyebrow}</p><h1>{p.title}</h1><p>{p.effective}</p><h2>{p.scanHeading}</h2><p>{p.scan}</p><h2>{p.aiHeading}</h2><p>{p.ai}</p><h2>{p.storageHeading}</h2><p>{p.storage}</p><p>{p.limits} <a href="https://github.com/sumei7550/SEO-Copilot/blob/main/docs/PRIVACY_DATA_MAP.md" target="_blank" rel="noopener noreferrer">data map</a>.</p><h2>{p.notHeading}</h2><ul>{p.notDo.map(item => <li key={item}>{item}</li>)}</ul><h2>{p.contact}</h2><p><a href="https://github.com/sumei7550/SEO-Copilot/issues" target="_blank" rel="noopener noreferrer">{p.contactLink}</a></p></div></main>; }
  if (path === 'support') { const s = getLocalizedSupport(lang); return <main className="page"><div className="wrap prose"><p className="eyebrow">{s.eyebrow}</p><h1>{s.title}</h1><p>{s.intro}</p><div className="faq">{s.faq.map(([q, a]) => <article className="card" key={q}><h3>{q}</h3><p>{a}</p></article>)}</div><div className="actions"><a className="button button-primary" href={STORE_URL} target="_blank" rel="noopener noreferrer">{s.install}</a><a className="button" href={localizedPath(lang, 'privacy')}>{s.privacy}</a><a className="button" href="https://github.com/sumei7550/SEO-Copilot/issues" target="_blank" rel="noopener noreferrer">{s.github}</a></div></div></main>; }
  const p = getPageCopy(lang, path); return <LandingPage eyebrow={p.eyebrow} title={p.title} intro={p.intro} bullets={p.bullets} what={p.what} reassurance={p.reassurance} cta={p.supportCta} related={relatedLinks(lang, path)} relatedLabel={p.related} />;
}
function LocalizedHome({ locale }: { locale: Locale }) { const c = getCopy(locale); return <main className="page localized-home"><div className="wrap prose"><p className="eyebrow">{c.eyebrow}</p><h1>{c.homeTitle}</h1><p className="hero-copy">{c.homeIntro}</p><div className="actions"><a className="button button-primary" href="https://chromewebstore.google.com/detail/kjkjgpmhjilegalgphglnagjnfgnighb?utm_source=website" target="_blank" rel="noopener noreferrer">{c.cta}</a></div><div className="cards localized-cards">{[c.score, c.issues, c.suggestions].map((x, i) => <article className="card" key={x}><div className="icon">0{i + 1}</div><h2>{x}</h2><p>{[c.howIntro, c.checks, c.privateBody][i]}</p></article>)}</div><div className="card landing-summary"><h2>{c.how}</h2><p>{c.howIntro}</p><ul><li>{c.score}</li><li>{c.issues}</li><li>{c.suggestions}</li></ul></div><div className="faq">{c.faq.map(([q, a]) => <article className="card" key={q}><h3>{q}</h3><p>{a}</p></article>)}</div></div></main>; }
