import Image from 'next/image';
import Link from 'next/link';
import { StoreCta } from '@/components/StoreCta';
import { getCopy, localizedPath, pageMetadata } from '@/lib/site';

export const metadata = pageMetadata('AI SEO Checker for the Page You Are Viewing', 'Scan a page locally, find SEO issues, and request grounded AI title and meta description suggestions.', '');

const coverage = ['Title tags', 'Meta descriptions', 'H1 & headings', 'Canonical links', 'Structured data', 'Image alt text', 'Readable URLs', 'Technical signals'];
const steps = [['01', 'Scan the page', 'Confirm the active page and get a local report.'], ['02', 'Read the score', 'See the overall health at a glance.'], ['03', 'Understand the issue', 'Know why a problem matters before acting.'], ['04', 'Ask for help', 'Request title or meta options only when you need them.'], ['05', 'Re-scan', 'Check whether your manual change improved the rule.']];

export default function Home() {
  const c = getCopy();
  return <main>
<section className="hero"><div className="wrap hero-grid"><div className="hero-copy-block"><p className="eyebrow">{c.eyebrow}</p><h1>Find the SEO issues holding your page back.</h1><p className="hero-copy">{c.homeIntro}</p><div className="actions"><StoreCta /><a className="button button-secondary" href="#how-it-works">See how it works</a></div><p className="note">{c.homeSub}</p></div><figure className="product-shot"><Image src="/screenshots/ai-seo-fix.png" alt="SEO Copilot showing an SEO issue and an AI title recommendation" width={709} height={857} priority /><figcaption>Real AI Fix result state</figcaption></figure></div></section>
<section className="section value-section"><div className="wrap"><div className="section-heading"><p className="eyebrow">What you get</p><h2>Useful answers before you change a thing.</h2><p>Start with the page-level signals that affect clarity, crawlability, and search appearance.</p></div><div className="cards value-cards">{[[c.score, 'See a focused 0–100 view of page health.'], [c.issues, 'Understand what is missing and why it matters.'], [c.suggestions, 'Generate title or meta description candidates only when you request them.']].map(([title, body], i) => <article className="card" key={title}><div className="icon">0{i + 1}</div><h3>{title}</h3><p>{body}</p></article>)}</div><div className="tool-links"><Link href={localizedPath('en', 'seo-checker')}>Check one page with SEO Checker</Link><Link href={localizedPath('en', 'seo-audit')}>Follow the SEO audit workflow</Link><Link href={localizedPath('en', 'title-tag-checker')}>Improve a title tag</Link><Link href={localizedPath('en', 'meta-description-checker')}>Improve a meta description</Link><Link href={localizedPath('en', 'on-page-seo-checker')}>Review on-page signals</Link></div></div></section>
    <section className="section product-proof section-soft"><div className="wrap proof-grid"><div className="proof-copy"><p className="eyebrow">See the result</p><h2>Know what to fix, and why.</h2><p>The report keeps the page in context: a score, prioritized issues, and explanations you can act on in your CMS or code.</p><Link className="text-link" href={localizedPath('en', 'features')}>Explore all features <span aria-hidden="true">→</span></Link></div><figure className="proof-shot"><Image src="/screenshots/seo-report.png" alt="SEO Copilot report with score and prioritized page issues" width={488} height={828} /><figcaption>Page-level SEO report</figcaption></figure></div></section>
    <section className="section" id="how-it-works"><div className="wrap"><div className="section-heading"><p className="eyebrow">How it works</p><h2>{c.how}</h2><p>{c.howIntro}</p></div><div className="steps">{steps.map(([number, title, body]) => <div className="step" key={number}><b>{number}</b><h3>{title}</h3><p>{body}</p></div>)}</div></div></section>
    <section className="section section-soft"><div className="wrap"><div className="section-heading"><p className="eyebrow">Coverage</p><h2>{c.checks}</h2><p>One focused report for the signals visible on the page you choose.</p></div><div className="checks">{coverage.map(item => <div className="check" key={item}><strong>{item}</strong><p>Included in the page-level audit.</p></div>)}</div></div></section>
    <section className="section trust-section"><div className="wrap trust-grid"><div><p className="eyebrow">{c.private}</p><h2>Helpful context, only when you choose.</h2></div><div><p>{c.privateBody}</p><Link className="text-link" href={localizedPath('en', 'privacy')}>Read the privacy policy <span aria-hidden="true">→</span></Link></div></div></section>
    <section className="section final-cta"><div className="wrap band"><div><p className="eyebrow">Start with the page in front of you.</p><h2>Make your next SEO check a short one.</h2><p>Install the extension, scan one page, and decide what deserves attention.</p></div><div className="actions"><StoreCta /><Link className="button button-secondary" href={localizedPath('en', 'support')}>Get support</Link></div></div></section>
  </main>;
}
