import type { Locale } from '@/lib/site';

export type LocalizedPrivacy = {
  eyebrow: string;
  title: string;
  effective: string;
  scanHeading: string;
  scan: string;
  aiHeading: string;
  ai: string;
  storageHeading: string;
  storage: string;
  limits: string;
  notHeading: string;
  notDo: string[];
  contact: string;
  contactLink: string;
};

export type LocalizedSupport = {
  eyebrow: string;
  title: string;
  intro: string;
  faq: [string, string][];
  install: string;
  privacy: string;
  github: string;
};

const privacy: Record<Locale, LocalizedPrivacy> = {
  en: { eyebrow: 'Privacy', title: 'Privacy at SEO Copilot', effective: 'Effective date: August 8, 2026', scanHeading: 'Basic SEO scanning', scan: 'When you explicitly analyze a page, SEO Copilot reads the active tab’s URL, metadata, headings, image SEO attributes, structured data, and visible text needed for the report. Basic SEO scanning runs locally in your browser.', aiHeading: 'Optional AI Fix', ai: 'AI Fix is optional. Only when you explicitly request a supported title or meta description suggestion does the extension send the necessary page context through the SEO Copilot backend to DeepSeek. The extension does not place an API key in the browser.', storageHeading: 'Storage and rate limits', storage: 'The extension uses a deviceId stored in chrome.storage.local. Upstash rate limiting uses the deviceId and IP to apply daily and short-term request limits and protect against abuse. IP is used only for rate limiting and abuse prevention. The backend is designed not to retain raw page content.', limits: 'No account is required for the basic audit. See the project’s latest data map for implementation details.', notHeading: 'What we do not do', notDo: ['We do not read cookies, passwords, payment details, or unrelated tabs.', 'We do not sell your data or use it for advertising.', 'We do not modify websites automatically.', 'We do not guarantee search rankings.'], contact: 'Questions?', contactLink: 'Open a support issue' },
  'zh-CN': { eyebrow: '隐私', title: 'SEO Copilot 隐私说明', effective: '生效日期：2026 年 8 月 8 日', scanHeading: '基础 SEO 扫描', scan: '只有在你主动分析页面时，SEO Copilot 才会读取当前标签页中生成报告所需的 URL、元数据、标题、图片 SEO 属性、结构化数据和可见文字。基础 SEO 扫描在浏览器本地运行。', aiHeading: '可选的 AI Fix', ai: 'AI Fix 是可选功能。只有在你明确请求受支持的标题或 Meta Description 建议时，扩展才会将必要的页面上下文通过 SEO Copilot backend 发送给 DeepSeek。扩展不会把 API key 放在浏览器中。', storageHeading: '存储与限流', storage: '扩展会将 deviceId 保存在 chrome.storage.local。Upstash rate limiting 使用 deviceId 和 IP 执行每日及短时请求限制，以保护服务并防止滥用。IP 仅用于限流和滥用防护。Backend 的设计不会保留原始页面内容。', limits: '基础审计无需账号。实现细节请参阅项目最新的 data map。', notHeading: '我们不会做什么', notDo: ['我们不会读取 Cookie、密码、支付信息或无关标签页。', '我们不会出售你的数据，也不会将其用于广告。', '我们不会自动修改网站。', '我们不保证搜索排名。'], contact: '有疑问？', contactLink: '前往 GitHub 提交支持 issue' },
  'zh-TW': { eyebrow: '隱私權', title: 'SEO Copilot 隱私權說明', effective: '生效日期：2026 年 8 月 8 日', scanHeading: '基礎 SEO 掃描', scan: '只有在你主動分析頁面時，SEO Copilot 才會讀取目前分頁中產生報告所需的 URL、中繼資料、標題、圖片 SEO 屬性、結構化資料與可見文字。基礎 SEO 掃描會在瀏覽器本機執行。', aiHeading: '可選的 AI Fix', ai: 'AI Fix 是選用功能。只有在你明確要求受支援的標題或 Meta Description 建議時，擴充功能才會將必要的頁面內容透過 SEO Copilot backend 傳送給 DeepSeek。擴充功能不會把 API key 放在瀏覽器中。', storageHeading: '儲存與限流', storage: '擴充功能會將 deviceId 儲存在 chrome.storage.local。Upstash rate limiting 使用 deviceId 與 IP 執行每日及短時間的請求限制，以保護服務並防止濫用。IP 僅用於限流與濫用防護。Backend 的設計不會保留原始頁面內容。', limits: '基礎稽核不需要帳號。實作細節請參閱專案最新的 data map。', notHeading: '我們不會做什麼', notDo: ['我們不會讀取 Cookie、密碼、付款資料或無關分頁。', '我們不會販售你的資料，也不會將其用於廣告。', '我們不會自動修改網站。', '我們不保證搜尋排名。'], contact: '有疑問嗎？', contactLink: '前往 GitHub 提交支援 issue' },
  ja: { eyebrow: 'プライバシー', title: 'SEO Copilot のプライバシー', effective: '発効日：2026年8月8日', scanHeading: '基本 SEO スキャン', scan: 'SEO Copilot は、あなたが明示的にページを分析した場合に限り、レポートに必要な現在のタブの URL、メタデータ、見出し、画像の SEO 属性、構造化データ、可視テキストを読み取ります。基本 SEO スキャンはブラウザ内でローカルに実行されます。', aiHeading: '任意の AI Fix', ai: 'AI Fix は任意の機能です。対応するタイトルまたはメタディスクリプションの提案を明示的にリクエストした場合に限り、拡張機能は必要なページコンテキストを SEO Copilot backend 経由で DeepSeek に送信します。API key をブラウザに置くことはありません。', storageHeading: '保存とレート制限', storage: '拡張機能は deviceId を chrome.storage.local に保存します。Upstash rate limiting は deviceId と IP を使って日次および短時間のリクエスト制限を適用し、サービスを保護して不正利用を防ぎます。IP はレート制限と不正利用の防止にのみ使用します。Backend はページの生データを保存しない設計です。', limits: '基本監査にアカウントは必要ありません。実装の詳細はプロジェクトの最新の data map をご覧ください。', notHeading: '行わないこと', notDo: ['Cookie、パスワード、支払い情報、関係のないタブは読み取りません。', 'データを販売したり、広告に利用したりしません。', 'ウェブサイトを自動で変更しません。', '検索順位を保証しません。'], contact: 'ご質問がありますか？', contactLink: 'GitHub でサポートを依頼する' },
  ko: { eyebrow: '개인정보 보호', title: 'SEO Copilot 개인정보 보호', effective: '시행일: 2026년 8월 8일', scanHeading: '기본 SEO 스캔', scan: 'SEO Copilot은 사용자가 명시적으로 페이지를 분석할 때만 현재 탭의 URL, 메타데이터, 헤딩, 이미지 SEO 속성, 구조화 데이터와 보고서에 필요한 본문을 읽습니다. 기본 SEO 스캔은 브라우저에서 로컬로 실행됩니다.', aiHeading: '선택 사항인 AI Fix', ai: 'AI Fix는 선택 기능입니다. 지원되는 제목 또는 메타 설명 제안을 명시적으로 요청한 경우에만 확장 프로그램이 필요한 페이지 컨텍스트를 SEO Copilot backend를 통해 DeepSeek으로 보냅니다. 브라우저에 API key를 저장하지 않습니다.', storageHeading: '저장 및 요청 제한', storage: '확장 프로그램은 deviceId를 chrome.storage.local에 저장합니다. Upstash rate limiting은 deviceId와 IP를 사용해 일일 및 단기 요청 제한을 적용하고 서비스 보호와 악용 방지를 지원합니다. IP는 요청 제한 및 악용 방지 목적으로만 사용됩니다. Backend는 원본 페이지 콘텐츠를 보관하지 않도록 설계되었습니다.', limits: '기본 감사에는 계정이 필요하지 않습니다. 구현 세부 정보는 프로젝트의 최신 data map에서 확인할 수 있습니다.', notHeading: '하지 않는 일', notDo: ['쿠키, 비밀번호, 결제 정보 또는 관련 없는 탭을 읽지 않습니다.', '데이터를 판매하거나 광고에 사용하지 않습니다.', '웹사이트를 자동으로 수정하지 않습니다.', '검색 순위를 보장하지 않습니다.'], contact: '궁금한 점이 있나요?', contactLink: 'GitHub에서 지원 요청하기' },
  de: { eyebrow: 'Datenschutz', title: 'Datenschutz bei SEO Copilot', effective: 'Gültig ab: 8. August 2026', scanHeading: 'Basisprüfung', scan: 'Wenn du eine Seite ausdrücklich analysierst, liest SEO Copilot die URL des aktiven Tabs sowie die für den Bericht nötigen Metadaten, Überschriften, Bild-SEO-Attribute, strukturierten Daten und sichtbaren Text. Die Basisprüfung läuft lokal im Browser.', aiHeading: 'Optionaler AI Fix', ai: 'AI Fix ist optional. Erst wenn du ausdrücklich einen unterstützten Titel- oder Meta-Description-Vorschlag anforderst, sendet die Erweiterung den nötigen Seitenkontext über das SEO Copilot backend an DeepSeek. Ein API key wird nicht im Browser abgelegt.', storageHeading: 'Speicherung und Limits', storage: 'Die Erweiterung speichert eine deviceId in chrome.storage.local. Upstash rate limiting nutzt deviceId und IP für tägliche und kurzfristige Anfrage-Limits, um den Dienst zu schützen und Missbrauch zu verhindern. Die IP wird ausschließlich für Rate-Limiting und Missbrauchsschutz verwendet. Das Backend ist so ausgelegt, dass es keine rohen Seiteninhalte speichert.', limits: 'Für das Basis-Audit ist kein Konto erforderlich. Einzelheiten zur Implementierung findest du in der aktuellen data map des Projekts.', notHeading: 'Was wir nicht tun', notDo: ['Wir lesen keine Cookies, Passwörter, Zahlungsdaten oder unabhängigen Tabs.', 'Wir verkaufen keine Daten und verwenden sie nicht für Werbung.', 'Wir ändern Websites nicht automatisch.', 'Wir garantieren keine Suchrankings.'], contact: 'Fragen?', contactLink: 'Support-Issue auf GitHub öffnen' },
  fr: { eyebrow: 'Confidentialité', title: 'La confidentialité chez SEO Copilot', effective: 'Date d’entrée en vigueur : 8 août 2026', scanHeading: 'Analyse SEO de base', scan: 'Lorsque vous analysez explicitement une page, SEO Copilot lit l’URL de l’onglet actif ainsi que les métadonnées, titres, attributs SEO des images, données structurées et textes visibles nécessaires au rapport. L’analyse SEO de base s’exécute localement dans le navigateur.', aiHeading: 'AI Fix facultatif', ai: 'AI Fix est facultatif. Ce n’est que lorsque vous demandez explicitement une suggestion de title ou de méta-description prise en charge que l’extension envoie le contexte de page nécessaire à DeepSeek via le SEO Copilot backend. Aucune API key n’est placée dans le navigateur.', storageHeading: 'Stockage et limites', storage: 'L’extension stocke un deviceId dans chrome.storage.local. Upstash rate limiting utilise le deviceId et l’IP pour appliquer des limites quotidiennes et à court terme, protéger le service et prévenir les abus. L’IP sert uniquement à la limitation des requêtes et à la prévention des abus. Le backend est conçu pour ne pas conserver le contenu brut des pages.', limits: 'Aucun compte n’est requis pour l’audit de base. Consultez la data map à jour du projet pour les détails d’implémentation.', notHeading: 'Ce que nous ne faisons pas', notDo: ['Nous ne lisons pas les cookies, mots de passe, données de paiement ni les onglets sans rapport.', 'Nous ne vendons pas vos données et ne les utilisons pas à des fins publicitaires.', 'Nous ne modifions pas automatiquement les sites web.', 'Nous ne garantissons pas le classement dans les résultats de recherche.'], contact: 'Une question ?', contactLink: 'Ouvrir une demande sur GitHub' },
  es: { eyebrow: 'Privacidad', title: 'Privacidad en SEO Copilot', effective: 'Fecha de entrada en vigor: 8 de agosto de 2026', scanHeading: 'Análisis SEO básico', scan: 'Cuando analizas una página de forma explícita, SEO Copilot lee la URL de la pestaña activa y los metadatos, encabezados, atributos SEO de las imágenes, datos estructurados y texto visible necesarios para el informe. El análisis SEO básico se ejecuta localmente en el navegador.', aiHeading: 'AI Fix opcional', ai: 'AI Fix es opcional. Solo cuando solicitas explícitamente una sugerencia compatible de título o meta descripción, la extensión envía el contexto necesario de la página a DeepSeek a través del SEO Copilot backend. La extensión no coloca ninguna API key en el navegador.', storageHeading: 'Almacenamiento y límites', storage: 'La extensión guarda un deviceId en chrome.storage.local. Upstash rate limiting utiliza el deviceId y la IP para aplicar límites diarios y de corto plazo, proteger el servicio y prevenir abusos. La IP se usa únicamente para limitar solicitudes y prevenir abusos. El backend está diseñado para no conservar el contenido bruto de las páginas.', limits: 'La auditoría básica no requiere una cuenta. Consulta la data map más reciente del proyecto para ver los detalles de implementación.', notHeading: 'Lo que no hacemos', notDo: ['No leemos cookies, contraseñas, datos de pago ni pestañas que no estén relacionadas.', 'No vendemos tus datos ni los usamos con fines publicitarios.', 'No modificamos sitios web automáticamente.', 'No garantizamos posiciones en los resultados de búsqueda.'], contact: '¿Tienes preguntas?', contactLink: 'Abrir una incidencia de soporte en GitHub' },
  'pt-BR': { eyebrow: 'Privacidade', title: 'Privacidade no SEO Copilot', effective: 'Data de vigência: 8 de agosto de 2026', scanHeading: 'Análise básica de SEO', scan: 'Quando você analisa uma página explicitamente, o SEO Copilot lê a URL da aba ativa e os metadados, headings, atributos de SEO das imagens, dados estruturados e texto visível necessários para o relatório. A análise básica de SEO é executada localmente no navegador.', aiHeading: 'AI Fix opcional', ai: 'O AI Fix é opcional. Somente quando você solicita explicitamente uma sugestão compatível de título ou meta description a extensão envia o contexto necessário da página ao DeepSeek por meio do SEO Copilot backend. A extensão não coloca uma API key no navegador.', storageHeading: 'Armazenamento e limites', storage: 'A extensão armazena um deviceId em chrome.storage.local. O Upstash rate limiting usa o deviceId e o IP para aplicar limites diários e de curto prazo, proteger o serviço e evitar abusos. O IP é usado somente para limitação de solicitações e prevenção de abusos. O backend foi projetado para não reter o conteúdo bruto das páginas.', limits: 'A auditoria básica não exige uma conta. Consulte a data map mais recente do projeto para detalhes de implementação.', notHeading: 'O que não fazemos', notDo: ['Não lemos cookies, senhas, dados de pagamento ou abas não relacionadas.', 'Não vendemos seus dados nem os usamos para publicidade.', 'Não modificamos sites automaticamente.', 'Não garantimos posições nos resultados de busca.'], contact: 'Tem alguma dúvida?', contactLink: 'Abrir uma solicitação de suporte no GitHub' },
};

const support: Record<Locale, LocalizedSupport> = {
  en: { eyebrow: 'Support', title: 'Need a hand?', intro: 'Find answers about scanning, AI Fix, installation, or report an issue. Please do not include private credentials or sensitive page content.', faq: [['Why can’t I scan a page?', 'Open a normal HTTP or HTTPS page, then click the extension and confirm the scan.'], ['Does it edit my website?', 'No. SEO Copilot gives recommendations and copy suggestions. You make the changes yourself.'], ['What does AI Fix support?', 'The current Alpha supports title and meta description suggestions. It does not automatically modify websites.'], ['Where can I report a bug?', 'Open an issue on the project’s GitHub support page with reproducible steps.']], install: 'Install from Chrome Web Store', privacy: 'Read the Privacy Policy', github: 'Open GitHub support ↗' },
  'zh-CN': { eyebrow: '支持', title: '需要帮助？', intro: '在这里了解扫描、AI Fix 和安装方式，也可以反馈问题。请不要提交密码等凭据或敏感页面内容。', faq: [['为什么无法扫描页面？', '请打开普通的 HTTP 或 HTTPS 页面，点击扩展图标，然后确认扫描。'], ['它会修改我的网站吗？', '不会。SEO Copilot 只提供建议和文案候选，由你自行修改网站。'], ['AI Fix 支持什么？', '当前 Alpha 支持标题和 Meta Description 建议，不会自动修改网站。'], ['在哪里反馈问题？', '请在项目的 GitHub 支持页面提交 issue，并附上可复现的操作步骤。']], install: '前往 Chrome Web Store 安装', privacy: '查看隐私说明', github: '打开 GitHub 支持页面 ↗' },
  'zh-TW': { eyebrow: '支援', title: '需要協助嗎？', intro: '在這裡了解掃描、AI Fix 與安裝方式，也可以回報問題。請勿提交密碼等憑證或敏感頁面內容。', faq: [['為什麼無法掃描頁面？', '請開啟一般的 HTTP 或 HTTPS 頁面，點擊擴充功能圖示，再確認掃描。'], ['它會修改我的網站嗎？', '不會。SEO Copilot 只提供建議與文案候選，由你自行修改網站。'], ['AI Fix 支援什麼？', '目前 Alpha 支援標題與 Meta Description 建議，不會自動修改網站。'], ['要在哪裡回報問題？', '請在專案的 GitHub 支援頁面提交 issue，並附上可重現的操作步驟。']], install: '前往 Chrome Web Store 安裝', privacy: '查看隱私權說明', github: '開啟 GitHub 支援頁面 ↗' },
  ja: { eyebrow: 'サポート', title: 'お困りですか？', intro: 'スキャン、AI Fix、インストールについて確認したり、問題を報告したりできます。パスワードなどの認証情報や機密性の高いページ内容は送らないでください。', faq: [['ページをスキャンできないのはなぜですか？', '通常の HTTP または HTTPS ページを開き、拡張機能をクリックしてスキャンを確認してください。'], ['ウェブサイトを編集しますか？', 'いいえ。SEO Copilot は提案と文章候補を表示します。変更はご自身で行ってください。'], ['AI Fix は何に対応していますか？', '現在の Alpha はタイトルとメタディスクリプションの提案に対応しています。ウェブサイトを自動で変更することはありません。'], ['不具合はどこに報告できますか？', 'プロジェクトの GitHub サポートページで、再現手順を添えて issue を開いてください。']], install: 'Chrome Web Store からインストール', privacy: 'プライバシーを確認', github: 'GitHub のサポートを開く ↗' },
  ko: { eyebrow: '지원', title: '도움이 필요하신가요?', intro: '스캔, AI Fix, 설치 방법을 확인하거나 문제를 신고할 수 있습니다. 비밀번호 같은 인증 정보나 민감한 페이지 내용은 보내지 마세요.', faq: [['페이지를 스캔할 수 없는 이유는 무엇인가요?', '일반 HTTP 또는 HTTPS 페이지를 열고 확장 프로그램을 클릭한 다음 스캔을 확인하세요.'], ['웹사이트를 수정하나요?', '아니요. SEO Copilot은 추천과 문구 후보를 제공합니다. 변경은 직접 수행하세요.'], ['AI Fix는 무엇을 지원하나요?', '현재 Alpha는 제목과 메타 설명 제안을 지원합니다. 웹사이트를 자동으로 수정하지 않습니다.'], ['버그는 어디에 신고하나요?', '프로젝트 GitHub 지원 페이지에 재현 가능한 단계를 적어 issue를 등록하세요.']], install: 'Chrome Web Store에서 설치', privacy: '개인정보 보호 정책 보기', github: 'GitHub 지원 열기 ↗' },
  de: { eyebrow: 'Support', title: 'Brauchst du Hilfe?', intro: 'Hier findest du Antworten zu Scan, AI Fix und Installation oder kannst ein Problem melden. Bitte sende keine Zugangsdaten oder vertraulichen Seiteninhalte.', faq: [['Warum kann ich eine Seite nicht scannen?', 'Öffne eine normale HTTP- oder HTTPS-Seite, klicke auf die Erweiterung und bestätige den Scan.'], ['Bearbeitet das Tool meine Website?', 'Nein. SEO Copilot liefert Empfehlungen und Textvorschläge. Du nimmst die Änderungen selbst vor.'], ['Was unterstützt AI Fix?', 'Die aktuelle Alpha unterstützt Vorschläge für Titel und Meta-Descriptions. Websites werden nicht automatisch geändert.'], ['Wo kann ich einen Fehler melden?', 'Öffne auf der GitHub-Supportseite des Projekts ein Issue und füge reproduzierbare Schritte hinzu.']], install: 'Im Chrome Web Store installieren', privacy: 'Datenschutzerklärung lesen', github: 'GitHub-Support öffnen ↗' },
  fr: { eyebrow: 'Assistance', title: 'Besoin d’aide ?', intro: 'Trouvez des réponses sur l’analyse, AI Fix et l’installation, ou signalez un problème. Ne transmettez pas d’identifiants ni de contenu sensible de page.', faq: [['Pourquoi une page ne peut-elle pas être analysée ?', 'Ouvrez une page HTTP ou HTTPS classique, cliquez sur l’extension, puis confirmez l’analyse.'], ['L’outil modifie-t-il mon site ?', 'Non. SEO Copilot fournit des recommandations et des textes possibles. Vous effectuez vous-même les changements.'], ['Que prend en charge AI Fix ?', 'L’Alpha actuelle propose des titres et des méta-descriptions. Elle ne modifie pas automatiquement les sites.'], ['Où signaler un bug ?', 'Ouvrez une issue sur la page GitHub d’assistance du projet avec des étapes reproductibles.']], install: 'Installer depuis le Chrome Web Store', privacy: 'Lire la politique de confidentialité', github: 'Ouvrir l’assistance GitHub ↗' },
  es: { eyebrow: 'Soporte', title: '¿Necesitas ayuda?', intro: 'Consulta respuestas sobre el análisis, AI Fix y la instalación, o informa de un problema. No envíes credenciales ni contenido sensible de la página.', faq: [['¿Por qué no puedo analizar una página?', 'Abre una página HTTP o HTTPS normal, haz clic en la extensión y confirma el análisis.'], ['¿La herramienta edita mi sitio?', 'No. SEO Copilot ofrece recomendaciones y textos candidatos. Tú haces los cambios.'], ['¿Qué admite AI Fix?', 'La Alpha actual propone títulos y meta descripciones. No modifica sitios web automáticamente.'], ['¿Dónde puedo informar de un error?', 'Abre una incidencia en la página de soporte de GitHub del proyecto e incluye pasos reproducibles.']], install: 'Instalar desde Chrome Web Store', privacy: 'Leer la política de privacidad', github: 'Abrir soporte de GitHub ↗' },
  'pt-BR': { eyebrow: 'Suporte', title: 'Precisa de ajuda?', intro: 'Encontre respostas sobre análise, AI Fix e instalação, ou relate um problema. Não envie credenciais nem conteúdo sensível da página.', faq: [['Por que não consigo analisar uma página?', 'Abra uma página HTTP ou HTTPS comum, clique na extensão e confirme a análise.'], ['A ferramenta edita meu site?', 'Não. O SEO Copilot oferece recomendações e textos candidatos. Você faz as alterações.'], ['O que o AI Fix oferece?', 'A Alpha atual sugere títulos e meta descriptions. Ela não modifica sites automaticamente.'], ['Onde posso relatar um bug?', 'Abra uma issue na página de suporte do GitHub do projeto e inclua etapas reproduzíveis.']], install: 'Instalar pela Chrome Web Store', privacy: 'Ler a política de privacidade', github: 'Abrir suporte no GitHub ↗' },
};

export function getLocalizedPrivacy(locale: Locale) { return privacy[locale] ?? privacy.en; }
export function getLocalizedSupport(locale: Locale) { return support[locale] ?? support.en; }
