import type { Metadata } from 'next';

const configuredSiteUrl = process.env.NEXT_PUBLIC_SITE_URL?.trim();
if (process.env.NODE_ENV === 'production' && !configuredSiteUrl) {
  throw new Error('NEXT_PUBLIC_SITE_URL must be set for a production website build.');
}
let parsedSiteUrl: URL;
try {
  parsedSiteUrl = new URL(configuredSiteUrl || 'http://localhost:3000');
} catch {
  throw new Error('NEXT_PUBLIC_SITE_URL must be a valid absolute URL such as https://example.com.');
}
if (!['http:', 'https:'].includes(parsedSiteUrl.protocol) || parsedSiteUrl.pathname !== '/' || parsedSiteUrl.search || parsedSiteUrl.hash) {
  throw new Error('NEXT_PUBLIC_SITE_URL must be an absolute HTTP(S) origin without a path, query, or hash.');
}
export const SITE_URL = parsedSiteUrl.toString().replace(/\/+$/, '');
export const OG_IMAGE_PATH = '/images/og/seo-copilot-og.svg';
export const STORE_URL = 'https://chromewebstore.google.com/detail/kjkjgpmhjilegalgphglnagjnfgnighb?utm_source=website';
export const LOCALES = ['zh-CN', 'zh-TW', 'ja', 'ko', 'de', 'fr', 'es', 'pt-BR'] as const;
export type Locale = 'en' | (typeof LOCALES)[number];
export const PATHS = ['', 'features', 'seo-checker', 'seo-audit', 'title-tag-checker', 'meta-description-checker', 'on-page-seo-checker', 'privacy', 'terms', 'support'];

const homeMetadata: Record<Locale, { title: string; description: string }> = {
  en: { title: 'AI SEO Checker for the Page You Are Viewing', description: 'Scan the page you are viewing, find SEO issues, and request grounded AI title and meta description suggestions when you need them.' },
  'zh-CN': { title: 'AI SEO 检查器｜SEO Copilot', description: '在浏览器中检查当前页面的 SEO 问题，并在需要时请求有依据的标题和 Meta 描述建议。' },
  'zh-TW': { title: 'AI SEO 檢查器｜SEO Copilot', description: '在瀏覽器中檢查目前頁面的 SEO 問題，並在需要時要求有依據的標題與 Meta 描述建議。' },
  ja: { title: 'AI SEO チェッカー｜SEO Copilot', description: '閲覧中のページをブラウザで確認し、SEO の問題と必要なときのタイトル・メタディスクリプション提案を表示します。' },
  ko: { title: 'AI SEO 검사 도구｜SEO Copilot', description: '브라우저에서 현재 페이지의 SEO 문제를 확인하고 필요할 때 제목과 메타 설명 제안을 요청하세요.' },
  de: { title: 'KI-gestützter SEO-Checker｜SEO Copilot', description: 'Prüfe die geöffnete Seite im Browser auf SEO-Probleme und fordere bei Bedarf passende Titel- und Meta-Description-Vorschläge an.' },
  fr: { title: 'Vérificateur SEO avec IA｜SEO Copilot', description: 'Analysez la page ouverte dans votre navigateur, repérez les problèmes SEO et demandez des suggestions de titre ou de méta-description si nécessaire.' },
  es: { title: 'Comprobador SEO con IA｜SEO Copilot', description: 'Analiza la página abierta en el navegador, detecta problemas SEO y pide sugerencias de título o meta descripción cuando las necesites.' },
  'pt-BR': { title: 'Verificador de SEO com IA｜SEO Copilot', description: 'Analise a página aberta no navegador, encontre problemas de SEO e peça sugestões de title ou meta description quando precisar.' },
};

export const uiLabels: Record<Locale, { product: string; resources: string; legal: string; seoChecker: string; privacy: string; terms: string; chromeStore: string }> = {
  en: { product: 'Product', resources: 'Resources', legal: 'Legal', seoChecker: 'SEO Checker', privacy: 'Privacy', terms: 'Terms', chromeStore: 'Chrome Web Store' },
  'zh-CN': { product: '产品', resources: '资源', legal: '法律', seoChecker: 'SEO 检查器', privacy: '隐私说明', terms: '使用条款', chromeStore: 'Chrome Web Store' },
  'zh-TW': { product: '產品', resources: '資源', legal: '法律', seoChecker: 'SEO 檢查器', privacy: '隱私權說明', terms: '使用條款', chromeStore: 'Chrome Web Store' },
  ja: { product: 'プロダクト', resources: 'リソース', legal: '法務', seoChecker: 'SEO チェッカー', privacy: 'プライバシー', terms: '利用規約', chromeStore: 'Chrome Web Store' },
  ko: { product: '제품', resources: '리소스', legal: '법률', seoChecker: 'SEO 검사 도구', privacy: '개인정보 보호', terms: '이용 약관', chromeStore: 'Chrome Web Store' },
  de: { product: 'Produkt', resources: 'Ressourcen', legal: 'Rechtliches', seoChecker: 'SEO-Checker', privacy: 'Datenschutz', terms: 'Nutzungsbedingungen', chromeStore: 'Chrome Web Store' },
  fr: { product: 'Produit', resources: 'Ressources', legal: 'Informations légales', seoChecker: 'Vérificateur SEO', privacy: 'Confidentialité', terms: 'Conditions', chromeStore: 'Chrome Web Store' },
  es: { product: 'Producto', resources: 'Recursos', legal: 'Legal', seoChecker: 'Comprobador SEO', privacy: 'Privacidad', terms: 'Términos', chromeStore: 'Chrome Web Store' },
  'pt-BR': { product: 'Produto', resources: 'Recursos', legal: 'Informações legais', seoChecker: 'Verificador de SEO', privacy: 'Privacidade', terms: 'Termos', chromeStore: 'Chrome Web Store' },
};

export function getHomeMetadata(locale: Locale) { return homeMetadata[locale] ?? homeMetadata.en; }

export const supportDescriptions: Record<Locale, string> = {
  en: 'Get installation help, troubleshoot scanning, learn about AI Fix, or report a problem with SEO Copilot.',
  'zh-CN': '了解 SEO Copilot 的安装、页面扫描、AI Fix 和问题反馈方式。',
  'zh-TW': '了解 SEO Copilot 的安裝、頁面掃描、AI Fix 與問題回報方式。',
  ja: 'SEO Copilot のインストール、ページスキャン、AI Fix、問題報告について確認できます。',
  ko: 'SEO Copilot 설치, 페이지 스캔, AI Fix 및 문제 신고 방법을 확인하세요.',
  de: 'Hilfe zur Installation, zum Seitenscan, zu AI Fix und zur Fehlerbehebung in SEO Copilot.',
  fr: 'Obtenez de l’aide pour l’installation, l’analyse, AI Fix ou le signalement d’un problème avec SEO Copilot.',
  es: 'Obtén ayuda con la instalación, el análisis, AI Fix o la comunicación de problemas en SEO Copilot.',
  'pt-BR': 'Encontre ajuda para instalar, analisar páginas, usar o AI Fix ou relatar problemas no SEO Copilot.',
};

const copy: Record<Locale, { name: string; nav: { features: string; audit: string; support: string }; cta: string; eyebrow: string; homeTitle: string; homeIntro: string; homeSub: string; score: string; issues: string; suggestions: string; how: string; howIntro: string; checks: string; private: string; privateBody: string; footer: string; faq: [string, string][] }> = {
  en: { name: 'SEO Copilot', nav: { features: 'Features', audit: 'SEO audit', support: 'Support' }, cta: 'Install on Chrome', eyebrow: 'AI-assisted page SEO', homeTitle: 'Find the SEO issues holding your page back.', homeIntro: 'SEO Copilot checks the page you are viewing, explains what matters, and gives you grounded title and meta description suggestions when you ask for them.', homeSub: 'Local page scan · No account for the basic audit · You stay in control', score: 'SEO score', issues: 'Issue detection', suggestions: 'AI title & meta suggestions', how: 'From scan to a better page', howIntro: 'A focused workflow for the page already in front of you.', checks: 'The essentials of on-page SEO', private: 'Private by default', privateBody: 'Basic scanning runs locally. AI suggestions are optional and use only the page context needed for the request. You apply any changes yourself, then re-scan.', footer: 'Practical SEO, right where you browse.', faq: [['Does SEO Copilot edit my website?', 'No. It gives recommendations and copy candidates. You make changes in your CMS or code, then re-scan.'], ['What does the AI do?', 'When you request it, the current Alpha can suggest titles and meta descriptions. It does not rewrite pages automatically.']] },
  'zh-CN': { name: 'SEO Copilot', nav: { features: '功能', audit: 'SEO 审计', support: '支持' }, cta: '安装到 Chrome', eyebrow: 'AI 辅助页面 SEO', homeTitle: '找出拖慢页面 SEO 表现的问题。', homeIntro: 'SEO Copilot 检查你正在浏览的页面，解释关键问题，并在你主动请求时提供有依据的标题和 Meta 描述建议。', homeSub: '页面扫描在本地完成 · 基础审计无需账号 · 修改由你掌控', score: 'SEO 评分', issues: '问题检测', suggestions: 'AI 标题与 Meta 建议', how: '从扫描到更好的页面', howIntro: '围绕当前页面的专注工作流。', checks: '页面 SEO 的核心要素', private: '默认保护隐私', privateBody: '基础扫描在浏览器本地执行。AI 建议是可选操作，只使用完成请求所需的页面上下文。修改由你手动完成，再重新扫描验证。', footer: '在浏览页面的同时，做好实用 SEO。', faq: [['SEO Copilot 会自动修改网站吗？', '不会。它提供建议和文案候选，你在 CMS 或代码中手动修改后再重新扫描。'], ['AI 能做什么？', '你主动请求后，当前 Alpha 可生成标题和 Meta 描述建议，不会自动重写页面。']] },
  'zh-TW': { name: 'SEO Copilot', nav: { features: '功能', audit: 'SEO 稽核', support: '支援' }, cta: '安裝到 Chrome', eyebrow: 'AI 輔助頁面 SEO', homeTitle: '找出拖慢頁面 SEO 表現的問題。', homeIntro: 'SEO Copilot 檢查你正在瀏覽的頁面，解釋重要問題，並在你主動要求時提供有依據的標題與 Meta 描述建議。', homeSub: '頁面掃描在本機完成 · 基礎稽核不需帳號 · 修改由你掌控', score: 'SEO 評分', issues: '問題偵測', suggestions: 'AI 標題與 Meta 建議', how: '從掃描到更好的頁面', howIntro: '圍繞目前頁面的專注工作流程。', checks: '頁面 SEO 的核心要素', private: '預設保護隱私', privateBody: '基礎掃描在瀏覽器本機執行。AI 建議是選用功能，只使用完成請求所需的頁面內容。修改由你手動完成，再重新掃描驗證。', footer: '瀏覽頁面的同時，做好實用 SEO。', faq: [['SEO Copilot 會自動修改網站嗎？', '不會。它提供建議和文案候選，你在 CMS 或程式碼中手動修改後再重新掃描。'], ['AI 能做什麼？', '主動要求後，現在的 Alpha 可產生標題和 Meta 描述建議，不會自動重寫頁面。']] },
  ja: { name: 'SEO Copilot', nav: { features: '機能', audit: 'SEO監査', support: 'サポート' }, cta: 'Chrome に追加', eyebrow: 'AI 支援のページ SEO', homeTitle: 'ページの SEO を妨げる問題を見つけます。', homeIntro: 'SEO Copilot は閲覧中のページを確認し、重要な問題を説明します。必要なときだけ、タイトルとメタディスクリプションの提案を生成できます。', homeSub: 'ページスキャンはローカル · 基本監査はアカウント不要 · 変更は自分で管理', score: 'SEO スコア', issues: '問題の検出', suggestions: 'AI タイトル・メタ提案', how: 'スキャンから改善まで', howIntro: 'いま開いているページに集中したワークフロー。', checks: 'オンページ SEO の基本', private: 'プライバシーを標準設定に', privateBody: '基本スキャンはブラウザ内で実行されます。AI 提案は任意で、リクエストに必要なページコンテキストだけを使います。変更は手動で行い、再スキャンで確認します。', footer: '閲覧中の場所で、実用的な SEO を。', faq: [['ウェブサイトを自動で編集しますか？', 'いいえ。提案と文章候補を表示します。CMS やコードを自分で変更し、再スキャンしてください。'], ['AI は何をしますか？', 'リクエストした場合、現在の Alpha はタイトルとメタディスクリプションを提案します。自動編集はしません。']] },
  ko: { name: 'SEO Copilot', nav: { features: '기능', audit: 'SEO 감사', support: '지원' }, cta: 'Chrome에 설치', eyebrow: 'AI 지원 페이지 SEO', homeTitle: '페이지 SEO를 방해하는 문제를 찾아보세요.', homeIntro: 'SEO Copilot은 현재 페이지를 점검하고 중요한 문제를 설명합니다. 필요할 때 제목과 메타 설명 제안을 받을 수 있습니다.', homeSub: '페이지 스캔은 로컬 처리 · 기본 감사는 계정 불필요 · 변경은 직접 관리', score: 'SEO 점수', issues: '문제 감지', suggestions: 'AI 제목 및 메타 제안', how: '스캔에서 개선까지', howIntro: '현재 페이지에 집중하는 간단한 작업 흐름입니다.', checks: '온페이지 SEO 핵심', private: '기본적으로 비공개', privateBody: '기본 스캔은 브라우저에서 로컬로 실행됩니다. AI 제안은 선택 사항이며 요청에 필요한 페이지 컨텍스트만 사용합니다. 직접 변경한 뒤 다시 스캔하세요.', footer: '탐색 중인 곳에서 실용적인 SEO를.', faq: [['웹사이트를 자동으로 수정하나요?', '아니요. 추천과 문구 후보를 제공합니다. CMS나 코드에서 직접 수정한 뒤 다시 스캔하세요.'], ['AI는 무엇을 하나요?', '요청하면 현재 Alpha가 제목과 메타 설명을 제안합니다. 페이지를 자동 수정하지 않습니다.']] },
  de: { name: 'SEO Copilot', nav: { features: 'Funktionen', audit: 'SEO-Audit', support: 'Support' }, cta: 'Zu Chrome hinzufügen', eyebrow: 'KI-gestützte On-Page-SEO', homeTitle: 'Finde die SEO-Probleme deiner Seite.', homeIntro: 'SEO Copilot prüft die geöffnete Seite, erklärt wichtige Probleme und erstellt auf Wunsch passende Titel- und Meta-Description-Vorschläge.', homeSub: 'Lokale Seitenprüfung · Kein Konto für das Basis-Audit · Du behältst die Kontrolle', score: 'SEO-Score', issues: 'Probleme erkennen', suggestions: 'KI-Titel- und Meta-Vorschläge', how: 'Vom Scan zur besseren Seite', howIntro: 'Ein fokussierter Ablauf für die gerade geöffnete Seite.', checks: 'Die Grundlagen der On-Page-SEO', private: 'Datenschutz als Standard', privateBody: 'Die Basisprüfung läuft lokal. KI-Vorschläge sind optional und verwenden nur den für die Anfrage nötigen Seitenkontext. Änderungen nimmst du selbst vor und prüfst sie anschließend erneut.', footer: 'Praktische SEO direkt beim Browsen.', faq: [['Bearbeitet SEO Copilot meine Website?', 'Nein. Das Tool liefert Empfehlungen und Textvorschläge. Du änderst die Seite selbst und startest danach einen neuen Scan.'], ['Was macht die KI?', 'Auf Anfrage schlägt die aktuelle Alpha Titel und Meta-Descriptions vor. Seiten werden nicht automatisch geändert.']] },
  fr: { name: 'SEO Copilot', nav: { features: 'Fonctionnalités', audit: 'Audit SEO', support: 'Assistance' }, cta: 'Ajouter à Chrome', eyebrow: 'SEO on-page assisté par IA', homeTitle: 'Trouvez les problèmes SEO qui freinent votre page.', homeIntro: 'SEO Copilot analyse la page ouverte, explique les points importants et propose, à votre demande, des titres et méta-descriptions adaptés.', homeSub: 'Analyse locale · Aucun compte pour l’audit de base · Vous gardez le contrôle', score: 'Score SEO', issues: 'Détection des problèmes', suggestions: 'Suggestions IA de titres et de méta', how: 'De l’analyse à une meilleure page', howIntro: 'Un parcours ciblé pour la page affichée.', checks: 'Les fondamentaux du SEO on-page', private: 'La confidentialité par défaut', privateBody: 'L’analyse de base s’exécute localement. Les suggestions IA sont facultatives et utilisent uniquement le contexte nécessaire. Vous appliquez les changements, puis relancez l’analyse.', footer: 'Un SEO pratique, au fil de votre navigation.', faq: [['SEO Copilot modifie-t-il mon site ?', 'Non. Il fournit des recommandations et des textes possibles. Vous effectuez les changements, puis relancez l’analyse.'], ['Que fait l’IA ?', 'Sur demande, l’Alpha actuelle propose des titres et méta-descriptions. Elle ne modifie pas automatiquement les pages.']] },
  es: { name: 'SEO Copilot', nav: { features: 'Funciones', audit: 'Auditoría SEO', support: 'Soporte' }, cta: 'Instalar en Chrome', eyebrow: 'SEO on-page con ayuda de IA', homeTitle: 'Encuentra los problemas SEO de tu página.', homeIntro: 'SEO Copilot revisa la página que estás viendo, explica lo importante y propone títulos y meta descripciones cuando tú lo pides.', homeSub: 'Análisis local · Sin cuenta para la auditoría básica · Tú controlas los cambios', score: 'Puntuación SEO', issues: 'Detección de problemas', suggestions: 'Sugerencias IA de títulos y meta', how: 'Del análisis a una página mejor', howIntro: 'Un flujo enfocado en la página que ya tienes abierta.', checks: 'Lo esencial del SEO on-page', private: 'Privacidad desde el inicio', privateBody: 'El análisis básico se ejecuta localmente. Las sugerencias de IA son opcionales y usan solo el contexto necesario. Tú aplicas los cambios y vuelves a analizar la página.', footer: 'SEO práctico, justo donde navegas.', faq: [['¿SEO Copilot edita mi sitio?', 'No. Ofrece recomendaciones y textos candidatos. Tú haces los cambios y vuelves a analizar.'], ['¿Qué hace la IA?', 'Cuando la solicitas, la Alpha actual propone títulos y meta descripciones. No modifica páginas automáticamente.']] },
  'pt-BR': { name: 'SEO Copilot', nav: { features: 'Recursos', audit: 'Auditoria SEO', support: 'Suporte' }, cta: 'Instalar no Chrome', eyebrow: 'SEO on-page com ajuda de IA', homeTitle: 'Encontre os problemas de SEO da sua página.', homeIntro: 'O SEO Copilot verifica a página aberta, explica o que importa e sugere títulos e meta descriptions quando você pedir.', homeSub: 'Análise local · Sem conta para a auditoria básica · Você controla as mudanças', score: 'Pontuação de SEO', issues: 'Detecção de problemas', suggestions: 'Sugestões de títulos e meta com IA', how: 'Da análise a uma página melhor', howIntro: 'Um fluxo focado na página que já está aberta.', checks: 'O essencial do SEO on-page', private: 'Privacidade por padrão', privateBody: 'A análise básica é executada localmente. As sugestões de IA são opcionais e usam apenas o contexto necessário. Você aplica as mudanças e faz uma nova análise.', footer: 'SEO prático, no lugar onde você navega.', faq: [['O SEO Copilot edita meu site?', 'Não. Ele oferece recomendações e textos candidatos. Você faz as mudanças e analisa novamente.'], ['O que a IA faz?', 'Quando solicitada, a Alpha atual sugere títulos e meta descriptions. Ela não modifica páginas automaticamente.']] },
};

export function getCopy(locale: Locale = 'en') { return copy[locale] ?? copy.en; }
export function localizedPath(locale: Locale, path: string) {
  const cleanPath = path.replace(/^\/+|\/+$/g, '');
  if (locale === 'en') return cleanPath ? `/${cleanPath}/` : '/';
  return cleanPath ? `/${locale}/${cleanPath}/` : `/${locale}/`;
}
export function absoluteUrl(locale: Locale, path: string) { return `${SITE_URL}${localizedPath(locale, path)}`; }
export function alternatesFor(path: string) {
  return {
    canonical: absoluteUrl('en', path),
    languages: Object.fromEntries((['en', ...LOCALES] as Locale[]).map((locale) => [locale, absoluteUrl(locale, path)]).concat([['x-default', absoluteUrl('en', path)]])),
  };
}
export function pageMetadata(title: string, description: string, path: string): Metadata {
  const url = absoluteUrl('en', path);
  return { title, description, alternates: alternatesFor(path), openGraph: { title: `${title} | SEO Copilot`, description, url, type: 'website', images: [{ url: OG_IMAGE_PATH, width: 1200, height: 630, alt: 'SEO Copilot page-level SEO checker' }] }, twitter: { card: 'summary_large_image', title: `${title} | SEO Copilot`, description, images: [OG_IMAGE_PATH] } };
}
export function jsonLdUrl(locale: Locale, path: string) { return absoluteUrl(locale, path); }

export type PageCopy = { eyebrow: string; title: string; intro: string; bullets: string[]; what: string; reassurance: string; related: string; privacy: { scan: string; ai: string; data: string; choices: string[] }; supportCta: string };
const pageCopy: Record<string, Partial<Record<Locale, PageCopy>>> = {
  features: {
    en: { eyebrow: 'Features', title: 'A clearer way to review a page.', intro: 'SEO Copilot keeps page-level SEO focused: find the signals that matter, understand the reason, then decide what to change.', bullets: ['Get a quick 0–100 SEO score for the page.', 'Find missing, weak, duplicated, or structurally inconsistent signals.', 'Request title or meta description ideas only when you want writing help.'], what: 'What you can do', reassurance: 'SEO Copilot is a page-level checker, not a full crawler or ranking platform. You make the change in your CMS or code, then re-scan.', related: 'Continue exploring', privacy: { scan: '', ai: '', data: '', choices: [] }, supportCta: 'Install on Chrome' },
    'zh-CN': { eyebrow: '功能', title: '更清晰地检查一个页面。', intro: 'SEO Copilot 聚焦页面级 SEO：找出重要信号，理解问题原因，再决定要改什么。', bullets: ['快速查看页面 0–100 SEO 评分。', '发现缺失、过短、过长、重复或结构不一致的问题。', '需要写作帮助时，再主动请求标题或 Meta 描述建议。'], what: '你可以做什么', reassurance: 'SEO Copilot 是页面级检查器，不是完整爬虫或排名平台。你在 CMS 或代码中手动修改，再重新扫描。', related: '继续探索', privacy: { scan: '', ai: '', data: '', choices: [] }, supportCta: '安装到 Chrome' },
    ja: { eyebrow: '機能', title: 'ページを、もっと分かりやすく確認。', intro: 'SEO Copilot はページ単位の SEO に集中し、重要なシグナルと理由を示してから、変更を判断できるようにします。', bullets: ['ページの SEO を 0〜100 で確認。', '不足、長さ、重複、構造上の問題を発見。', '文章の相談が必要なときだけ、タイトルやメタディスクリプションを提案。'], what: 'できること', reassurance: 'SEO Copilot はページ単位のチェッカーで、クローラーや順位計測ツールではありません。CMS やコードを自分で変更し、再スキャンします。', related: 'さらに見る', privacy: { scan: '', ai: '', data: '', choices: [] }, supportCta: 'Chrome に追加' },
    de: { eyebrow: 'Funktionen', title: 'Seiten-SEO klarer prüfen.', intro: 'SEO Copilot konzentriert sich auf die wichtigsten Signale der geöffneten Seite, erklärt die Ursache und hilft dir bei der nächsten Entscheidung.', bullets: ['Den SEO-Score der Seite auf einen Blick sehen.', 'Fehlende, zu kurze, zu lange oder doppelte Signale erkennen.', 'Titel- und Meta-Description-Ideen nur auf Anfrage erstellen.'], what: 'Das kannst du tun', reassurance: 'SEO Copilot ist ein Seiten-Checker, kein vollständiger Crawler und keine Ranking-Plattform. Du änderst die Seite selbst und scannst erneut.', related: 'Mehr entdecken', privacy: { scan: '', ai: '', data: '', choices: [] }, supportCta: 'Zu Chrome hinzufügen' },
    fr: { eyebrow: 'Fonctionnalités', title: 'Analyser une page plus clairement.', intro: 'SEO Copilot se concentre sur les signaux SEO de la page ouverte, explique les problèmes et vous aide à choisir la prochaine action.', bullets: ['Voir rapidement un score SEO de 0 à 100.', 'Repérer les éléments manquants, trop courts, trop longs ou dupliqués.', 'Demander des idées de titre ou de méta-description uniquement si nécessaire.'], what: 'Ce que vous pouvez faire', reassurance: 'SEO Copilot est un vérificateur page par page, pas un crawler complet ni un outil de classement. Vous effectuez les changements, puis relancez l’analyse.', related: 'À découvrir', privacy: { scan: '', ai: '', data: '', choices: [] }, supportCta: 'Ajouter à Chrome' },
    es: { eyebrow: 'Funciones', title: 'Revisa cada página con más claridad.', intro: 'SEO Copilot se centra en las señales SEO de la página abierta, explica los problemas y te ayuda a decidir qué cambiar.', bullets: ['Consulta rápidamente una puntuación SEO de 0 a 100.', 'Detecta elementos ausentes, cortos, largos, duplicados o mal estructurados.', 'Pide ideas para títulos o meta descripciones solo cuando necesites ayuda.'], what: 'Qué puedes hacer', reassurance: 'SEO Copilot es un comprobador por página, no un rastreador completo ni una plataforma de posiciones. Tú haces los cambios y vuelves a analizar.', related: 'Seguir explorando', privacy: { scan: '', ai: '', data: '', choices: [] }, supportCta: 'Instalar en Chrome' },
    ko: { eyebrow: '기능', title: '페이지를 더 명확하게 점검하세요.', intro: 'SEO Copilot은 중요한 페이지 SEO 신호를 찾고 이유를 설명한 뒤 무엇을 바꿀지 결정하도록 돕습니다.', bullets: ['페이지의 SEO 점수를 0~100으로 확인합니다.', '누락되거나 짧거나 길거나 중복된 문제를 찾습니다.', '필요할 때만 제목과 메타 설명 아이디어를 요청합니다.'], what: '할 수 있는 일', reassurance: 'SEO Copilot은 페이지 검사 도구이며 전체 크롤러나 순위 플랫폼이 아닙니다. 직접 수정하고 다시 스캔하세요.', related: '더 살펴보기', privacy: { scan: '', ai: '', data: '', choices: [] }, supportCta: 'Chrome에 설치' },
    'pt-BR': { eyebrow: 'Recursos', title: 'Revise uma página com mais clareza.', intro: 'O SEO Copilot foca nos sinais de SEO da página, explica os problemas e ajuda você a decidir o que mudar.', bullets: ['Veja rapidamente uma pontuação de SEO de 0 a 100.', 'Encontre sinais ausentes, curtos, longos, duplicados ou inconsistentes.', 'Peça ideias de title ou meta description somente quando precisar.'], what: 'O que você pode fazer', reassurance: 'O SEO Copilot é um verificador por página, não um crawler completo nem uma plataforma de posições. Você faz a mudança e analisa novamente.', related: 'Continuar explorando', privacy: { scan: '', ai: '', data: '', choices: [] }, supportCta: 'Instalar no Chrome' },
  },
};
const pageLabels: Record<Locale, [string, string, string]> = {
  en: ['Review the page-level signals that matter.', 'Understand the impact before you change anything.', 'Make the change yourself, then re-scan to verify.'],
  'zh-CN': ['检查影响页面表现的 SEO 信号。', '先了解影响，再决定是否修改。', '手动完成修改，再重新扫描验证。'], 'zh-TW': ['檢查影響頁面表現的 SEO 訊號。', '先了解影響，再決定是否修改。', '手動完成修改，再重新掃描驗證。'], ja: ['ページにある重要な SEO シグナルを確認。', '変更前に、その影響を理解。', '自分で変更し、再スキャンで確認。'], ko: ['페이지의 중요한 SEO 신호를 확인합니다.', '변경하기 전에 영향을 이해합니다.', '직접 변경한 뒤 다시 스캔합니다.'], de: ['Wichtige SEO-Signale der Seite prüfen.', 'Die Auswirkungen vor der Änderung verstehen.', 'Selbst ändern und danach erneut scannen.'], fr: ['Vérifier les signaux SEO importants de la page.', 'Comprendre l’impact avant de modifier.', 'Modifier vous-même, puis relancer l’analyse.'], es: ['Revisar las señales SEO importantes de la página.', 'Entender el impacto antes de cambiar nada.', 'Hacer el cambio y volver a analizar.'], 'pt-BR': ['Verificar os sinais de SEO importantes da página.', 'Entender o impacto antes de alterar algo.', 'Fazer a mudança e analisar novamente.'],
};
export function getPageCopy(locale: Locale, path: string): PageCopy {
  const localized = pageCopy.features?.[locale] ?? pageCopy.features?.en!;
  const base = { ...localized, bullets: [...localized.bullets] };
  if (path === 'features') return base;
  const c = getCopy(locale); const labels = pageLabels[locale];
  const heads: Record<Locale, Record<string, [string, string, string]>> = {
    en: { 'seo-checker': ['SEO Checker', 'Check the SEO health of the page you are viewing.', 'A focused checker for a quick score, prioritized issues, and useful next steps.'], 'seo-audit': ['SEO Audit', 'A practical SEO audit for the page in front of you.', 'Review key on-page signals without a crawler or complex dashboard.'], 'title-tag-checker': ['Title tag checker', 'Make your page title clearer before you publish.', 'Find title issues, then request grounded alternatives.'], 'meta-description-checker': ['Meta description checker', 'Give searchers a useful reason to click.', 'Check the description, then request concise alternatives.'], 'on-page-seo-checker': ['On-page SEO checker', 'Review the SEO signals that live on the page.', 'Review metadata, headings, images, canonical, schema, and URLs.'] },
    'zh-CN': { 'seo-checker': ['SEO 检查器', '检查你正在浏览的页面的 SEO 状况。', '快速查看评分、重点问题和可执行的下一步。'], 'seo-audit': ['SEO 审计', '为当前页面进行实用的 SEO 审计。', '无需爬虫或复杂后台，即可查看关键页面信号。'], 'title-tag-checker': ['Title 标签检查', '发布前，让页面标题更清晰。', '发现 title 问题，并在需要时请求有依据的替代方案。'], 'meta-description-checker': ['Meta Description 检查', '给搜索用户一个值得点击的理由。', '检查描述问题，并在需要时请求简洁的替代方案。'], 'on-page-seo-checker': ['页面 SEO 检查', '检查页面本身包含的 SEO 信号。', '集中查看元数据、标题、图片、canonical、结构化数据和 URL。'] },
    'zh-TW': { 'seo-checker': ['SEO 檢查器', '檢查你正在瀏覽的頁面 SEO 狀況。', '快速查看評分、重點問題與可執行的下一步。'], 'seo-audit': ['SEO 稽核', '為目前頁面進行實用的 SEO 稽核。', '不需爬蟲或複雜後台，即可查看關鍵頁面訊號。'], 'title-tag-checker': ['Title 標籤檢查', '發布前，讓頁面標題更清楚。', '找出 title 問題，並在需要時要求有依據的替代方案。'], 'meta-description-checker': ['Meta Description 檢查', '給搜尋者一個值得點擊的理由。', '檢查描述問題，並在需要時要求精簡替代方案。'], 'on-page-seo-checker': ['頁面 SEO 檢查', '檢查頁面本身的 SEO 訊號。', '集中查看中繼資料、標題、圖片、canonical、結構化資料與 URL。'] },
    ja: { 'seo-checker': ['SEO チェッカー', '閲覧中のページの SEO 状態を確認。', 'スコア、優先度の高い問題、次のアクションを確認できます。'], 'seo-audit': ['SEO 監査', '目の前のページを実用的に監査。', 'クローラーや複雑なダッシュボードなしで重要なシグナルを確認します。'], 'title-tag-checker': ['タイトルタグチェッカー', '公開前にページタイトルを明確に。', 'title の問題を見つけ、必要なら候補をリクエストします。'], 'meta-description-checker': ['メタディスクリプションチェッカー', '検索ユーザーにクリックする理由を伝える。', '説明文を確認し、必要なら簡潔な候補をリクエストします。'], 'on-page-seo-checker': ['オンページ SEO チェッカー', 'ページ上の SEO シグナルを確認。', 'メタデータ、見出し、画像、canonical、構造化データ、URL を確認します。'] },
    ko: { 'seo-checker': ['SEO 검사 도구', '현재 페이지의 SEO 상태를 확인하세요.', '점수와 우선순위 문제, 다음 작업을 빠르게 확인합니다.'], 'seo-audit': ['SEO 감사', '현재 페이지를 실용적으로 감사하세요.', '크롤러나 복잡한 대시보드 없이 주요 신호를 확인합니다.'], 'title-tag-checker': ['Title 태그 검사', '게시 전에 페이지 제목을 더 명확하게 만드세요.', 'title 문제를 찾고 필요할 때 대안을 요청합니다.'], 'meta-description-checker': ['Meta Description 검사', '검색 사용자에게 클릭할 이유를 알려주세요.', '설명을 확인하고 필요할 때 간결한 대안을 요청합니다.'], 'on-page-seo-checker': ['온페이지 SEO 검사', '페이지에 있는 SEO 신호를 확인하세요.', '메타데이터, 헤딩, 이미지, canonical, 구조화 데이터와 URL을 확인합니다.'] },
    de: { 'seo-checker': ['SEO-Checker', 'Prüfe die SEO-Gesundheit der geöffneten Seite.', 'Score, priorisierte Probleme und nächste Schritte auf einen Blick.'], 'seo-audit': ['SEO-Audit', 'Ein praktisches SEO-Audit für die geöffnete Seite.', 'Wichtige On-Page-Signale ohne Crawler oder komplexes Dashboard prüfen.'], 'title-tag-checker': ['Title-Tag-Checker', 'Mach den Seitentitel vor der Veröffentlichung klarer.', 'Title-Probleme finden und bei Bedarf passende Alternativen anfordern.'], 'meta-description-checker': ['Meta-Description-Checker', 'Gib Suchenden einen guten Grund zu klicken.', 'Die Beschreibung prüfen und bei Bedarf kurze Alternativen anfordern.'], 'on-page-seo-checker': ['On-Page-SEO-Checker', 'Prüfe die SEO-Signale direkt auf der Seite.', 'Metadaten, Überschriften, Bilder, Canonical, strukturierte Daten und URLs prüfen.'] },
    fr: { 'seo-checker': ['Vérificateur SEO', 'Vérifiez la santé SEO de la page ouverte.', 'Consultez le score, les problèmes prioritaires et les prochaines actions.'], 'seo-audit': ['Audit SEO', 'Un audit SEO pratique pour la page affichée.', 'Vérifiez les signaux on-page sans crawler ni tableau de bord complexe.'], 'title-tag-checker': ['Vérificateur de balise title', 'Clarifiez le titre avant de publier.', 'Repérez les problèmes de title et demandez des alternatives si besoin.'], 'meta-description-checker': ['Vérificateur de méta-description', 'Donnez aux internautes une bonne raison de cliquer.', 'Vérifiez la description et demandez des variantes concises si besoin.'], 'on-page-seo-checker': ['Vérificateur SEO on-page', 'Vérifiez les signaux SEO présents sur la page.', 'Analysez métadonnées, titres, images, canonical, données structurées et URL.'] },
    es: { 'seo-checker': ['Comprobador SEO', 'Comprueba la salud SEO de la página que ves.', 'Consulta la puntuación, los problemas prioritarios y los siguientes pasos.'], 'seo-audit': ['Auditoría SEO', 'Una auditoría SEO práctica para la página abierta.', 'Revisa las señales on-page sin rastreador ni panel complejo.'], 'title-tag-checker': ['Comprobador de title', 'Aclara el título de tu página antes de publicar.', 'Detecta problemas del title y pide alternativas cuando las necesites.'], 'meta-description-checker': ['Comprobador de meta descripción', 'Da a los usuarios un buen motivo para hacer clic.', 'Revisa la descripción y pide alternativas concisas si las necesitas.'], 'on-page-seo-checker': ['Comprobador de SEO on-page', 'Revisa las señales SEO de la propia página.', 'Comprueba metadatos, encabezados, imágenes, canonical, datos estructurados y URL.'] },
    'pt-BR': { 'seo-checker': ['Verificador de SEO', 'Confira a saúde de SEO da página aberta.', 'Veja a pontuação, os problemas prioritários e os próximos passos.'], 'seo-audit': ['Auditoria de SEO', 'Uma auditoria prática para a página aberta.', 'Revise sinais on-page sem crawler ou painel complexo.'], 'title-tag-checker': ['Verificador de title tag', 'Deixe o título da página mais claro antes de publicar.', 'Encontre problemas no title e peça alternativas quando precisar.'], 'meta-description-checker': ['Verificador de meta description', 'Dê às pessoas um bom motivo para clicar.', 'Confira a descrição e peça alternativas concisas quando quiser.'], 'on-page-seo-checker': ['Verificador de SEO on-page', 'Revise os sinais de SEO presentes na página.', 'Confira metadados, headings, imagens, canonical, dados estruturados e URLs.'] },
  };
  const common = heads[locale];
  const [eyebrow, title, intro] = common[path] ?? common['seo-checker'];
  return { ...base, eyebrow, title, intro, bullets: labels, what: base.what, reassurance: locale === 'en' ? base.reassurance : `${base.reassurance} ${locale === 'ja' ? '自動編集や順位保証はありません。' : locale === 'de' ? 'Seiten werden nicht automatisch geändert; Rankings werden nicht garantiert.' : locale === 'fr' ? 'Les pages ne sont pas modifiées automatiquement et aucun classement n’est garanti.' : locale === 'es' ? 'No se editan páginas automáticamente ni se garantizan posiciones.' : locale === 'ko' ? '페이지를 자동으로 수정하지 않으며 순위를 보장하지 않습니다.' : locale === 'pt-BR' ? 'As páginas não são alteradas automaticamente e não há garantia de posições.' : '不会自动修改网站，也不保证排名。'}`, related: base.related, privacy: { scan: '', ai: '', data: '', choices: [] }, supportCta: c.cta };
}
