'use client';
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { getCopy, localizedPath, LOCALES, type Locale } from '@/lib/site';
const languageNames: Record<Locale, string> = { en: 'English', 'zh-CN': '简体中文', 'zh-TW': '繁體中文', ja: '日本語', ko: '한국어', de: 'Deutsch', fr: 'Français', es: 'Español', 'pt-BR': 'Português (Brasil)' };
const allLocales: Locale[] = ['en', ...LOCALES];
export function Header({ locale = 'en', currentPath = '' }: { locale?: Locale; currentPath?: string }) {
  const c = getCopy(locale); const [mobileOpen, setMobileOpen] = useState(false); const [languageOpen, setLanguageOpen] = useState(false); const languageRef = useRef<HTMLDivElement>(null);
  useEffect(() => { if (!mobileOpen) return; const previousOverflow = document.body.style.overflow; document.body.style.overflow = 'hidden'; return () => { document.body.style.overflow = previousOverflow; }; }, [mobileOpen]);
  useEffect(() => { const down = (event: MouseEvent) => { if (!languageRef.current?.contains(event.target as Node)) setLanguageOpen(false); }; const key = (event: KeyboardEvent) => { if (event.key === 'Escape') { setLanguageOpen(false); setMobileOpen(false); } }; document.addEventListener('mousedown', down); document.addEventListener('keydown', key); return () => { document.removeEventListener('mousedown', down); document.removeEventListener('keydown', key); }; }, []);
  const closeMobile = () => { setMobileOpen(false); setLanguageOpen(false); };
  return <header className="site-header"><div className="wrap header-inner"><Link className="brand" href={localizedPath(locale, '')} aria-label="SEO Copilot home" onClick={closeMobile}><img className="brand-mark" src="/icon128.png" alt="" width={32} height={32} /><span>SEO Copilot</span></Link><nav className="nav" aria-label="Primary navigation"><Link href={localizedPath(locale, 'features')}>{c.nav.features}</Link><Link href={localizedPath(locale, 'seo-audit')}>{c.nav.audit}</Link><Link href={localizedPath(locale, 'support')}>{c.nav.support}</Link><span className="nav-disabled" aria-disabled="true" title="Coming soon">Pricing</span><LanguagePicker locale={locale} currentPath={currentPath} open={languageOpen} setOpen={setLanguageOpen} languageRef={languageRef} /><InstallLink label="Add to Chrome" /></nav><button className="mobile-menu-toggle" type="button" aria-expanded={mobileOpen} aria-controls="mobile-navigation" onClick={() => { setMobileOpen(!mobileOpen); setLanguageOpen(false); }}><span className="menu-icon" aria-hidden="true"><i /><i /><i /></span><span>{mobileOpen ? 'Close' : 'Menu'}</span></button></div>{mobileOpen && <div className="mobile-menu-panel" id="mobile-navigation"><nav className="mobile-nav" aria-label="Mobile navigation"><Link href={localizedPath(locale, 'features')} onClick={closeMobile}>{c.nav.features}<span aria-hidden="true">↗</span></Link><Link href={localizedPath(locale, 'seo-audit')} onClick={closeMobile}>{c.nav.audit}<span aria-hidden="true">↗</span></Link><Link href={localizedPath(locale, 'support')} onClick={closeMobile}>{c.nav.support}<span aria-hidden="true">↗</span></Link><span className="mobile-nav-disabled" aria-disabled="true">Pricing <small>Coming soon</small></span></nav><div className="mobile-menu-divider" /><div className="mobile-language-block"><span className="mobile-language-label">Language</span><LanguagePicker locale={locale} currentPath={currentPath} open={languageOpen} setOpen={setLanguageOpen} languageRef={languageRef} mobile /></div><InstallLink label="Add to Chrome" onClick={closeMobile} /></div>}</header>;
}
function LanguagePicker({ locale, currentPath, open, setOpen, languageRef, mobile = false }: { locale: Locale; currentPath: string; open: boolean; setOpen: (value: boolean) => void; languageRef: React.RefObject<HTMLDivElement | null>; mobile?: boolean }) { return <div className={`language-picker${mobile ? ' language-picker-mobile' : ''}`} ref={languageRef}><button className="language-button" type="button" aria-label="Choose language" aria-haspopup="menu" aria-expanded={open} onClick={() => setOpen(!open)}>{!mobile && <GlobeIcon />}<span>{mobile ? languageNames[locale] : locale === 'en' ? 'English' : languageNames[locale]}</span><ChevronIcon open={open} /></button>{open && <div className="language-menu" role="menu" aria-label="Choose language">{allLocales.map(item => <Link role="menuitem" aria-current={item === locale ? 'true' : undefined} className={item === locale ? 'selected' : ''} key={item} href={localizedPath(item, currentPath)} onClick={() => setOpen(false)}><span>{languageNames[item]}</span>{item === locale && <span aria-hidden="true">✓</span>}</Link>)}</div>}</div>; }
function InstallLink({ label, onClick }: { label: string; onClick?: () => void }) { return <a className="button button-primary install-button" href="https://chromewebstore.google.com/detail/kjkjgpmhjilegalgphglnagjnfgnighb?utm_source=website" target="_blank" rel="noopener noreferrer" onClick={onClick}><ChromeIcon />{label}</a>; }
function ChromeIcon() { return <svg className="chrome-icon" aria-hidden="true" viewBox="0 0 24 24" width="18" height="18"><defs><clipPath id="chrome-clip-header"><circle cx="12" cy="12" r="10" /></clipPath></defs><g clipPath="url(#chrome-clip-header)"><path fill="#ea4335" d="M12 2a10 10 0 0 1 8.66 5H12a5 5 0 0 0-4.33 2.5L4.96 5A10 10 0 0 1 12 2Z" /><path fill="#fbbc05" d="M20.66 7A10 10 0 0 1 12 22l4.33-7.5A5 5 0 0 0 12 12H6.57L3.34 7h17.32Z" /><path fill="#34a853" d="M12 22A10 10 0 0 1 4.96 5l4.33 7.5A5 5 0 0 0 12 17h4.33L12 22Z" /></g><circle cx="12" cy="12" r="4.1" fill="#4285f4" stroke="#fff" strokeWidth="1.4" /><circle cx="12" cy="12" r="10" fill="none" stroke="#fff" strokeOpacity=".6" strokeWidth=".7" /></svg>; }
function GlobeIcon() { return <svg className="globe-icon" aria-hidden="true" viewBox="0 0 24 24" width="19" height="19" fill="none"><circle cx="12" cy="12" r="9" stroke="currentColor" strokeWidth="1.7" /><path d="M3.5 12h17M12 3c2.2 2.4 3.3 5.4 3.3 9s-1.1 6.6-3.3 9c-2.2-2.4-3.3-5.4-3.3-9S9.8 5.4 12 3Z" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" /></svg>; }
function ChevronIcon({ open }: { open: boolean }) { return <svg className={`chevron${open ? ' is-open' : ''}`} aria-hidden="true" viewBox="0 0 12 8" width="12" height="8" fill="none"><path d="m1 1 5 5 5-5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></svg>; }
