import Image from 'next/image';
import Link from 'next/link';
import { StoreCta } from '@/components/StoreCta';
import { getCopy, localizedPath, type Locale } from '@/lib/site';

const coverage = ['Title tags', 'Meta descriptions', 'H1 & headings', 'Canonical links', 'Structured data', 'Image alt text', 'Readable URLs', 'Technical signals'];
const storeAlt = 'SEO Copilot showing an SEO issue and an AI title recommendation';
const reportAlt = 'SEO Copilot report with score and prioritized page issues';

type HomeUi = { what: string; intro: string; values: [string, string, string]; result: string; resultBody: string; steps: [string, string, string][]; coverage: string; included: string; privacy: string; privacyLink: string; final: [string, string, string]; support: string };

const homeUi: Record<Locale, HomeUi> = {
  en: { what: 'What you get', intro: 'Start with the page-level signals that affect clarity, crawlability, and search appearance.', values: ['See a focused 0–100 view of page health.', 'Understand what is missing and why it matters.', 'Generate title or meta description candidates only when you request them.'], result: 'Know what to fix, and why.', resultBody: 'The report keeps the page in context: a score, prioritized issues, and explanations you can act on in your CMS or code.', steps: [['01', 'Scan the page', 'Confirm the active page and get a local report.'], ['02', 'Read the score', 'See the overall health at a glance.'], ['03', 'Understand the issue', 'Know why a problem matters before acting.'], ['04', 'Ask for help', 'Request title or meta options only when you need them.'], ['05', 'Re-scan', 'Check whether your manual change improved the rule.']], coverage: 'One focused report for the signals visible on the page you choose.', included: 'Included in the page-level audit.', privacy: 'Helpful context, only when you choose.', privacyLink: 'Read the privacy policy', final: ['Start with the page in front of you.', 'Make your next SEO check a short one.', 'Install the extension, scan one page, and decide what deserves attention.'], support: 'Get support' },
  'zh-CN': { what: '你将获得什么', intro: '从影响页面清晰度、可抓取性和搜索展示的页面级信号开始。', values: ['用 0–100 的聚焦评分快速了解页面健康度。', '了解缺少什么，以及它为什么重要。', '只有在你请求时，才生成标题或 Meta 描述候选。'], result: '知道该修什么，以及为什么。', resultBody: '报告保留页面上下文：展示评分、优先问题和可在 CMS 或代码中执行的解释。', steps: [['01', '扫描页面', '确认当前页面并获取本地报告。'], ['02', '查看评分', '快速了解页面整体健康度。'], ['03', '理解问题', '在修改前了解问题为什么重要。'], ['04', '请求帮助', '需要时请求标题或 Meta 描述选项。'], ['05', '重新扫描', '检查手动修改是否改善了规则结果。']], coverage: '围绕所选页面可见 SEO 信号的一份聚焦报告。', included: '包含在页面级审计中。', privacy: '只在你选择时提供必要的页面上下文。', privacyLink: '查看隐私说明', final: ['从当前打开的页面开始。', '让下一次 SEO 检查变得更简单。', '安装扩展，扫描一个页面，然后决定哪些问题值得优先处理。'], support: '获取支持' },
  'zh-TW': { what: '你會獲得什麼', intro: '從影響頁面清晰度、可抓取性與搜尋呈現的頁面級訊號開始。', values: ['用 0–100 的聚焦評分快速了解頁面健康度。', '了解缺少什麼，以及它為什麼重要。', '只有在你要求時，才產生標題或 Meta 描述候選。'], result: '知道該修什麼，以及為什麼。', resultBody: '報告保留頁面脈絡：展示評分、優先問題與可在 CMS 或程式碼中執行的說明。', steps: [['01', '掃描頁面', '確認目前頁面並取得本機報告。'], ['02', '查看評分', '快速了解頁面整體健康度。'], ['03', '理解問題', '修改前先了解問題為什麼重要。'], ['04', '要求協助', '需要時要求標題或 Meta 描述選項。'], ['05', '重新掃描', '檢查手動修改是否改善規則結果。']], coverage: '圍繞所選頁面可見 SEO 訊號的一份聚焦報告。', included: '包含在頁面級稽核中。', privacy: '只在你選擇時提供必要的頁面內容。', privacyLink: '查看隱私權說明', final: ['從目前開啟的頁面開始。', '讓下一次 SEO 檢查變得更簡單。', '安裝擴充功能，掃描一個頁面，再決定哪些問題值得優先處理。'], support: '取得支援' },
  ja: { what: 'できること', intro: 'ページの明確さ、クロール性、検索結果での表示に関わるシグナルから確認できます。', values: ['0〜100 のスコアでページの状態をすばやく確認できます。', '不足しているものと、その理由を理解できます。', '必要なときだけタイトルやメタディスクリプションの候補を生成できます。'], result: '何を直すべきか、その理由まで分かります。', resultBody: 'スコア、優先度の高い問題、CMS やコードで対応できる説明をページの文脈とともに表示します。', steps: [['01', 'ページをスキャン', '現在のページを確認し、ローカルレポートを取得します。'], ['02', 'スコアを見る', 'ページ全体の状態をひと目で確認します。'], ['03', '問題を理解', '変更する前に問題の重要性を確認します。'], ['04', '提案を依頼', '必要なときだけタイトルやメタの候補を依頼します。'], ['05', '再スキャン', '手動の変更でルールが改善したか確認します。']], coverage: '選択したページで確認できるシグナルをまとめたレポートです。', included: 'ページ単位の監査に含まれます。', privacy: '選択したときだけ、必要なコンテキストを使います。', privacyLink: 'プライバシーを確認', final: ['いま開いているページから始めましょう。', '次の SEO チェックを短く済ませます。', '拡張機能をインストールしてページをスキャンし、対応すべき問題を決めましょう。'], support: 'サポートを見る' },
  ko: { what: '제공되는 기능', intro: '페이지의 명확성, 크롤링 가능성, 검색 결과 표시와 관련된 페이지 단위 신호부터 확인합니다.', values: ['0–100 점수로 페이지 상태를 빠르게 확인합니다.', '무엇이 부족한지, 왜 중요한지 이해합니다.', '필요할 때만 제목이나 메타 설명 후보를 생성합니다.'], result: '무엇을 고쳐야 하는지, 왜 그런지 알 수 있습니다.', resultBody: '점수, 우선순위 문제, CMS나 코드에서 실행할 수 있는 설명을 페이지 맥락과 함께 보여줍니다.', steps: [['01', '페이지 스캔', '현재 페이지를 확인하고 로컬 보고서를 받습니다.'], ['02', '점수 확인', '페이지의 전체 상태를 한눈에 봅니다.'], ['03', '문제 이해', '수정하기 전에 문제가 중요한 이유를 확인합니다.'], ['04', '도움 요청', '필요할 때만 제목이나 메타 옵션을 요청합니다.'], ['05', '다시 스캔', '직접 수정한 내용이 규칙을 개선했는지 확인합니다.']], coverage: '선택한 페이지에 보이는 신호를 한 번에 확인하는 보고서입니다.', included: '페이지 단위 감사에 포함됩니다.', privacy: '선택할 때만 필요한 페이지 컨텍스트를 사용합니다.', privacyLink: '개인정보 보호 정책 보기', final: ['현재 열려 있는 페이지에서 시작하세요.', '다음 SEO 검사를 짧게 끝내세요.', '확장 프로그램을 설치하고 한 페이지를 스캔한 뒤 우선 처리할 문제를 결정하세요.'], support: '지원 받기' },
  de: { what: 'Das bekommst du', intro: 'Starte mit den Seitensignalen, die Klarheit, Crawlbarkeit und die Darstellung in der Suche beeinflussen.', values: ['Sieh den Zustand der Seite als Score von 0–100.', 'Verstehe, was fehlt und warum es wichtig ist.', 'Erstelle Titel- oder Meta-Description-Vorschläge nur auf Anfrage.'], result: 'Erkenne, was du ändern solltest – und warum.', resultBody: 'Der Bericht zeigt Score, priorisierte Probleme und Erklärungen, die du in CMS oder Code umsetzen kannst.', steps: [['01', 'Seite prüfen', 'Bestätige die aktuelle Seite und erhalte einen lokalen Bericht.'], ['02', 'Score lesen', 'Sieh den Gesamtzustand auf einen Blick.'], ['03', 'Problem verstehen', 'Verstehe vor der Änderung, warum ein Problem zählt.'], ['04', 'Hilfe anfordern', 'Fordere Optionen nur bei Bedarf an.'], ['05', 'Erneut prüfen', 'Kontrolliere, ob deine Änderung die Regel verbessert hat.']], coverage: 'Ein fokussierter Bericht zu den sichtbaren Signalen der ausgewählten Seite.', included: 'Im Seiten-Audit enthalten.', privacy: 'Kontext nur dann, wenn du ihn anforderst.', privacyLink: 'Datenschutzerklärung lesen', final: ['Starte mit der gerade geöffneten Seite.', 'Mach deinen nächsten SEO-Check kurz.', 'Installiere die Erweiterung, prüfe eine Seite und entscheide, was Aufmerksamkeit verdient.'], support: 'Support öffnen' },
  fr: { what: 'Ce que vous obtenez', intro: 'Commencez par les signaux de la page qui influencent la clarté, l’exploration et l’apparence dans les résultats.', values: ['Consultez un score ciblé de 0 à 100.', 'Comprenez ce qui manque et pourquoi c’est important.', 'Générez des titres ou méta-descriptions uniquement à votre demande.'], result: 'Sachez quoi corriger et pourquoi.', resultBody: 'Le rapport conserve le contexte de la page : score, problèmes prioritaires et explications exploitables dans votre CMS ou votre code.', steps: [['01', 'Analyser la page', 'Confirmez la page ouverte et obtenez un rapport local.'], ['02', 'Lire le score', 'Visualisez l’état général en un coup d’œil.'], ['03', 'Comprendre le problème', 'Sachez pourquoi un problème compte avant d’agir.'], ['04', 'Demander une aide', 'Demandez des options uniquement si nécessaire.'], ['05', 'Relancer l’analyse', 'Vérifiez si votre modification a amélioré la règle.']], coverage: 'Un rapport ciblé sur les signaux visibles de la page choisie.', included: 'Inclus dans l’audit de la page.', privacy: 'Le contexte utile, uniquement quand vous le choisissez.', privacyLink: 'Lire la politique de confidentialité', final: ['Commencez par la page ouverte.', 'Faites de votre prochain contrôle SEO une étape simple.', 'Installez l’extension, analysez une page et décidez ce qui mérite votre attention.'], support: 'Obtenir de l’aide' },
  es: { what: 'Qué obtienes', intro: 'Empieza por las señales de la página que afectan a la claridad, el rastreo y su apariencia en las búsquedas.', values: ['Consulta una puntuación enfocada de 0 a 100.', 'Entiende qué falta y por qué importa.', 'Genera títulos o meta descripciones solo cuando las solicites.'], result: 'Sabe qué corregir y por qué.', resultBody: 'El informe mantiene el contexto de la página: puntuación, problemas prioritarios y explicaciones aplicables en tu CMS o código.', steps: [['01', 'Analiza la página', 'Confirma la página actual y obtén un informe local.'], ['02', 'Lee la puntuación', 'Consulta el estado general de un vistazo.'], ['03', 'Entiende el problema', 'Descubre por qué importa antes de actuar.'], ['04', 'Pide ayuda', 'Solicita opciones solo cuando las necesites.'], ['05', 'Vuelve a analizar', 'Comprueba si tu cambio mejoró la regla.']], coverage: 'Un informe enfocado en las señales visibles de la página que eliges.', included: 'Incluido en la auditoría de la página.', privacy: 'Contexto útil, solo cuando tú lo eliges.', privacyLink: 'Leer la política de privacidad', final: ['Empieza por la página que tienes abierta.', 'Haz más breve tu próxima comprobación SEO.', 'Instala la extensión, analiza una página y decide qué merece atención.'], support: 'Obtener soporte' },
  'pt-BR': { what: 'O que você recebe', intro: 'Comece pelos sinais da página que afetam clareza, rastreabilidade e aparência nos resultados de busca.', values: ['Veja uma visão focada de 0 a 100 sobre a saúde da página.', 'Entenda o que está faltando e por que isso importa.', 'Gere candidatos de title ou meta description somente quando solicitar.'], result: 'Saiba o que corrigir e por quê.', resultBody: 'O relatório mantém o contexto da página: pontuação, problemas prioritários e explicações aplicáveis no CMS ou no código.', steps: [['01', 'Analise a página', 'Confirme a página atual e obtenha um relatório local.'], ['02', 'Leia a pontuação', 'Veja a saúde geral de uma só vez.'], ['03', 'Entenda o problema', 'Saiba por que um problema importa antes de agir.'], ['04', 'Peça ajuda', 'Solicite opções somente quando precisar.'], ['05', 'Analise novamente', 'Confira se sua alteração melhorou a regra.']], coverage: 'Um relatório focado nos sinais visíveis da página escolhida.', included: 'Incluído na auditoria da página.', privacy: 'Contexto útil, somente quando você escolher.', privacyLink: 'Ler a política de privacidade', final: ['Comece pela página que está aberta.', 'Faça da próxima verificação de SEO uma etapa curta.', 'Instale a extensão, analise uma página e decida o que merece atenção.'], support: 'Obter suporte' },
};

export function LocalizedHome({ locale }: { locale: Locale }) {
  const c = getCopy(locale); const ui = homeUi[locale];
  return <main>
    <section className="hero"><div className="wrap hero-grid"><div className="hero-copy-block"><p className="eyebrow">{c.eyebrow}</p><h1>{c.homeTitle}</h1><p className="hero-copy">{c.homeIntro}</p><div className="actions"><StoreCta label={c.cta} /><a className="button button-secondary" href="#how-it-works">{c.how}</a></div><p className="note">{c.homeSub}</p></div><figure className="product-shot"><Image src="/screenshots/ai-seo-fix.png" alt={storeAlt} width={709} height={857} priority /><figcaption>{ui.result}</figcaption></figure></div></section>
    <section className="section value-section"><div className="wrap"><div className="section-heading"><p className="eyebrow">{ui.what}</p><h2>{ui.intro}</h2><p>{c.homeIntro}</p></div><div className="cards value-cards">{[c.score, c.issues, c.suggestions].map((title, i) => <article className="card" key={title}><div className="icon">0{i + 1}</div><h3>{title}</h3><p>{ui.values[i]}</p></article>)}</div><div className="tool-links"><Link href={localizedPath(locale, 'seo-checker')}>{c.score}</Link><Link href={localizedPath(locale, 'seo-audit')}>{c.nav.audit}</Link><Link href={localizedPath(locale, 'title-tag-checker')}>{c.suggestions}</Link><Link href={localizedPath(locale, 'meta-description-checker')}>{c.suggestions}</Link><Link href={localizedPath(locale, 'on-page-seo-checker')}>{c.checks}</Link></div></div></section>
    <section className="section product-proof section-soft"><div className="wrap proof-grid"><div className="proof-copy"><p className="eyebrow">{ui.result}</p><h2>{ui.result}</h2><p>{ui.resultBody}</p><Link className="text-link" href={localizedPath(locale, 'features')}>{c.nav.features} <span aria-hidden="true">→</span></Link></div><figure className="proof-shot"><Image src="/screenshots/seo-report.png" alt={reportAlt} width={488} height={828} /><figcaption>{c.checks}</figcaption></figure></div></section>
    <section className="section" id="how-it-works"><div className="wrap"><div className="section-heading"><p className="eyebrow">{c.how}</p><h2>{c.how}</h2><p>{c.howIntro}</p></div><div className="steps">{ui.steps.map(([number, title, body]) => <div className="step" key={number}><b>{number}</b><h3>{title}</h3><p>{body}</p></div>)}</div></div></section>
    <section className="section section-soft"><div className="wrap"><div className="section-heading"><p className="eyebrow">{c.checks}</p><h2>{c.checks}</h2><p>{ui.coverage}</p></div><div className="checks">{coverage.map(item => <div className="check" key={item}><strong>{item}</strong><p>{ui.included}</p></div>)}</div></div></section>
    <section className="section trust-section"><div className="wrap trust-grid"><div><p className="eyebrow">{c.private}</p><h2>{ui.privacy}</h2></div><div><p>{c.privateBody}</p><Link className="text-link" href={localizedPath(locale, 'privacy')}>{ui.privacyLink} <span aria-hidden="true">→</span></Link></div></div></section>
    <section className="section final-cta"><div className="wrap band"><div><p className="eyebrow">{ui.final[0]}</p><h2>{ui.final[1]}</h2><p>{ui.final[2]}</p></div><div className="actions"><StoreCta label={c.cta} /><Link className="button button-secondary" href={localizedPath(locale, 'support')}>{ui.support}</Link></div></div></section>
  </main>;
}
